/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import java.util.List;
import msharpmodel.Activity;
import msharpmodel.Company;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class ActivityResult {

    private String companyId;
    private boolean confirmed;
    private boolean countAsApptConfirmed;
    private boolean countAsApptCreated;
    private boolean countAsContacted;
    private String createdBy;
    private Date createdDate;
    private boolean emailFailure;
    private boolean emailSuccess;
    private int id;
    private boolean isActive;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String name;
    private List<Activity> activity;
    private Company company;

    /**
     * Constructor without parameter.
     * 
     */
    public ActivityResult() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public ActivityResult(int id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "confirmed" attribute.
    *
    * @return The value of the "confirmed" attribute.
    */
   public boolean getConfirmed() {
      return confirmed;
   }
   /**
    * Returns the value of the "countAsApptConfirmed" attribute.
    *
    * @return The value of the "countAsApptConfirmed" attribute.
    */
   public boolean getCountAsApptConfirmed() {
      return countAsApptConfirmed;
   }
   /**
    * Returns the value of the "countAsApptCreated" attribute.
    *
    * @return The value of the "countAsApptCreated" attribute.
    */
   public boolean getCountAsApptCreated() {
      return countAsApptCreated;
   }
   /**
    * Returns the value of the "countAsContacted" attribute.
    *
    * @return The value of the "countAsContacted" attribute.
    */
   public boolean getCountAsContacted() {
      return countAsContacted;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "emailFailure" attribute.
    *
    * @return The value of the "emailFailure" attribute.
    */
   public boolean getEmailFailure() {
      return emailFailure;
   }
   /**
    * Returns the value of the "emailSuccess" attribute.
    *
    * @return The value of the "emailSuccess" attribute.
    */
   public boolean getEmailSuccess() {
      return emailSuccess;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public int getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "activity" attribute.
    *
    * @return The value of the "activity" attribute.
    */
   public List<Activity> getActivity() {
      return activity;
   }
   
   /**
    * Returns the value of the "company" attribute.
    *
    * @return The value of the "company" attribute.
    */
   public Company getCompany() {
      return company;
   }
   
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "confirmed" attribute.
    *
    * @param confirmed
    *     The value of the "confirmed" attribute.
    */
   public void setConfirmed(boolean confirmed) {
      this.confirmed = confirmed;
   }
   /**
    * Sets the value of the "countAsApptConfirmed" attribute.
    *
    * @param countAsApptConfirmed
    *     The value of the "countAsApptConfirmed" attribute.
    */
   public void setCountAsApptConfirmed(boolean countAsApptConfirmed) {
      this.countAsApptConfirmed = countAsApptConfirmed;
   }
   /**
    * Sets the value of the "countAsApptCreated" attribute.
    *
    * @param countAsApptCreated
    *     The value of the "countAsApptCreated" attribute.
    */
   public void setCountAsApptCreated(boolean countAsApptCreated) {
      this.countAsApptCreated = countAsApptCreated;
   }
   /**
    * Sets the value of the "countAsContacted" attribute.
    *
    * @param countAsContacted
    *     The value of the "countAsContacted" attribute.
    */
   public void setCountAsContacted(boolean countAsContacted) {
      this.countAsContacted = countAsContacted;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "emailFailure" attribute.
    *
    * @param emailFailure
    *     The value of the "emailFailure" attribute.
    */
   public void setEmailFailure(boolean emailFailure) {
      this.emailFailure = emailFailure;
   }
   /**
    * Sets the value of the "emailSuccess" attribute.
    *
    * @param emailSuccess
    *     The value of the "emailSuccess" attribute.
    */
   public void setEmailSuccess(boolean emailSuccess) {
      this.emailSuccess = emailSuccess;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(int id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "activity" attribute.
    *
    * @param activity"
    *     The value of the "activity" attribute.
    */
   public void setActivity(List<Activity> activity) {
      this.activity = activity;
   }

   /**
    * Sets the value of the "company" attribute.
    *
    * @param company"
    *     The value of the "company" attribute.
    */
   public void setCompany(Company company) {
      this.company = company;
   }

}