/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import java.util.List;
import msharpmodel.ActivityReference;
import msharpmodel.ActivityResult;
import msharpmodel.Appointment;
import msharpmodel.C800responseLead;
import msharpmodel.Contact;
import msharpmodel.Inquiry;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Activity {

    private int activityReferenceId;
    private int activityResultId;
    private String appointmentId;
    private String assignToEmployeeId;
    private Date completedDate;
    private String contactId;
    private String createdBy;
    private Date createdDate;
    private Date dueDate;
    private String id;
    private String inquiryId;
    private boolean isActive;
    private Date lastUpdate;
    private String lastUpdatedBy;
    private String name;
    private String notes;
    private boolean reminderDismissed;
    private int reminderMinutes;
    private String scheduledByEmployeeId;
    private String type;
    private ActivityReference activityReference;
    private ActivityResult activityResult;
    private Appointment appointment;
    private List<C800responseLead> c800responseLead;
    private Contact contact;
    private Inquiry inquiry;

    /**
     * Constructor without parameter.
     * 
     */
    public Activity() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Activity(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "activityReferenceId" attribute.
    *
    * @return The value of the "activityReferenceId" attribute.
    */
   public int getActivityReferenceId() {
      return activityReferenceId;
   }
   /**
    * Returns the value of the "activityResultId" attribute.
    *
    * @return The value of the "activityResultId" attribute.
    */
   public int getActivityResultId() {
      return activityResultId;
   }
   /**
    * Returns the value of the "appointmentId" attribute.
    *
    * @return The value of the "appointmentId" attribute.
    */
   public String getAppointmentId() {
      return appointmentId;
   }
   /**
    * Returns the value of the "assignToEmployeeId" attribute.
    *
    * @return The value of the "assignToEmployeeId" attribute.
    */
   public String getAssignToEmployeeId() {
      return assignToEmployeeId;
   }
   /**
    * Returns the value of the "completedDate" attribute.
    *
    * @return The value of the "completedDate" attribute.
    */
   public Date getCompletedDate() {
      return completedDate;
   }
   /**
    * Returns the value of the "contactId" attribute.
    *
    * @return The value of the "contactId" attribute.
    */
   public String getContactId() {
      return contactId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "dueDate" attribute.
    *
    * @return The value of the "dueDate" attribute.
    */
   public Date getDueDate() {
      return dueDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "inquiryId" attribute.
    *
    * @return The value of the "inquiryId" attribute.
    */
   public String getInquiryId() {
      return inquiryId;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdatedBy" attribute.
    *
    * @return The value of the "lastUpdatedBy" attribute.
    */
   public String getLastUpdatedBy() {
      return lastUpdatedBy;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "notes" attribute.
    *
    * @return The value of the "notes" attribute.
    */
   public String getNotes() {
      return notes;
   }
   /**
    * Returns the value of the "reminderDismissed" attribute.
    *
    * @return The value of the "reminderDismissed" attribute.
    */
   public boolean getReminderDismissed() {
      return reminderDismissed;
   }
   /**
    * Returns the value of the "reminderMinutes" attribute.
    *
    * @return The value of the "reminderMinutes" attribute.
    */
   public int getReminderMinutes() {
      return reminderMinutes;
   }
   /**
    * Returns the value of the "scheduledByEmployeeId" attribute.
    *
    * @return The value of the "scheduledByEmployeeId" attribute.
    */
   public String getScheduledByEmployeeId() {
      return scheduledByEmployeeId;
   }
   /**
    * Returns the value of the "type" attribute.
    *
    * @return The value of the "type" attribute.
    */
   public String getType() {
      return type;
   }
   /**
    * Returns the value of the "activityReference" attribute.
    *
    * @return The value of the "activityReference" attribute.
    */
   public ActivityReference getActivityReference() {
      return activityReference;
   }
   
   /**
    * Returns the value of the "activityResult" attribute.
    *
    * @return The value of the "activityResult" attribute.
    */
   public ActivityResult getActivityResult() {
      return activityResult;
   }
   
   /**
    * Returns the value of the "appointment" attribute.
    *
    * @return The value of the "appointment" attribute.
    */
   public Appointment getAppointment() {
      return appointment;
   }
   
   /**
    * Returns the value of the "c800responseLead" attribute.
    *
    * @return The value of the "c800responseLead" attribute.
    */
   public List<C800responseLead> getC800responseLead() {
      return c800responseLead;
   }
   
   /**
    * Returns the value of the "contact" attribute.
    *
    * @return The value of the "contact" attribute.
    */
   public Contact getContact() {
      return contact;
   }
   
   /**
    * Returns the value of the "inquiry" attribute.
    *
    * @return The value of the "inquiry" attribute.
    */
   public Inquiry getInquiry() {
      return inquiry;
   }
   
   /**
    * Sets the value of the "activityReferenceId" attribute.
    *
    * @param activityReferenceId
    *     The value of the "activityReferenceId" attribute.
    */
   public void setActivityReferenceId(int activityReferenceId) {
      this.activityReferenceId = activityReferenceId;
   }
   /**
    * Sets the value of the "activityResultId" attribute.
    *
    * @param activityResultId
    *     The value of the "activityResultId" attribute.
    */
   public void setActivityResultId(int activityResultId) {
      this.activityResultId = activityResultId;
   }
   /**
    * Sets the value of the "appointmentId" attribute.
    *
    * @param appointmentId
    *     The value of the "appointmentId" attribute.
    */
   public void setAppointmentId(String appointmentId) {
      this.appointmentId = appointmentId;
   }
   /**
    * Sets the value of the "assignToEmployeeId" attribute.
    *
    * @param assignToEmployeeId
    *     The value of the "assignToEmployeeId" attribute.
    */
   public void setAssignToEmployeeId(String assignToEmployeeId) {
      this.assignToEmployeeId = assignToEmployeeId;
   }
   /**
    * Sets the value of the "completedDate" attribute.
    *
    * @param completedDate
    *     The value of the "completedDate" attribute.
    */
   public void setCompletedDate(Date completedDate) {
      this.completedDate = completedDate;
   }
   /**
    * Sets the value of the "contactId" attribute.
    *
    * @param contactId
    *     The value of the "contactId" attribute.
    */
   public void setContactId(String contactId) {
      this.contactId = contactId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "dueDate" attribute.
    *
    * @param dueDate
    *     The value of the "dueDate" attribute.
    */
   public void setDueDate(Date dueDate) {
      this.dueDate = dueDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "inquiryId" attribute.
    *
    * @param inquiryId
    *     The value of the "inquiryId" attribute.
    */
   public void setInquiryId(String inquiryId) {
      this.inquiryId = inquiryId;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdatedBy" attribute.
    *
    * @param lastUpdatedBy
    *     The value of the "lastUpdatedBy" attribute.
    */
   public void setLastUpdatedBy(String lastUpdatedBy) {
      this.lastUpdatedBy = lastUpdatedBy;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "notes" attribute.
    *
    * @param notes
    *     The value of the "notes" attribute.
    */
   public void setNotes(String notes) {
      this.notes = notes;
   }
   /**
    * Sets the value of the "reminderDismissed" attribute.
    *
    * @param reminderDismissed
    *     The value of the "reminderDismissed" attribute.
    */
   public void setReminderDismissed(boolean reminderDismissed) {
      this.reminderDismissed = reminderDismissed;
   }
   /**
    * Sets the value of the "reminderMinutes" attribute.
    *
    * @param reminderMinutes
    *     The value of the "reminderMinutes" attribute.
    */
   public void setReminderMinutes(int reminderMinutes) {
      this.reminderMinutes = reminderMinutes;
   }
   /**
    * Sets the value of the "scheduledByEmployeeId" attribute.
    *
    * @param scheduledByEmployeeId
    *     The value of the "scheduledByEmployeeId" attribute.
    */
   public void setScheduledByEmployeeId(String scheduledByEmployeeId) {
      this.scheduledByEmployeeId = scheduledByEmployeeId;
   }
   /**
    * Sets the value of the "type" attribute.
    *
    * @param type
    *     The value of the "type" attribute.
    */
   public void setType(String type) {
      this.type = type;
   }
   /**
    * Sets the value of the "activityReference" attribute.
    *
    * @param activityReference"
    *     The value of the "activityReference" attribute.
    */
   public void setActivityReference(ActivityReference activityReference) {
      this.activityReference = activityReference;
   }

   /**
    * Sets the value of the "activityResult" attribute.
    *
    * @param activityResult"
    *     The value of the "activityResult" attribute.
    */
   public void setActivityResult(ActivityResult activityResult) {
      this.activityResult = activityResult;
   }

   /**
    * Sets the value of the "appointment" attribute.
    *
    * @param appointment"
    *     The value of the "appointment" attribute.
    */
   public void setAppointment(Appointment appointment) {
      this.appointment = appointment;
   }

   /**
    * Sets the value of the "c800responseLead" attribute.
    *
    * @param c800responseLead"
    *     The value of the "c800responseLead" attribute.
    */
   public void setC800responseLead(List<C800responseLead> c800responseLead) {
      this.c800responseLead = c800responseLead;
   }

   /**
    * Sets the value of the "contact" attribute.
    *
    * @param contact"
    *     The value of the "contact" attribute.
    */
   public void setContact(Contact contact) {
      this.contact = contact;
   }

   /**
    * Sets the value of the "inquiry" attribute.
    *
    * @param inquiry"
    *     The value of the "inquiry" attribute.
    */
   public void setInquiry(Inquiry inquiry) {
      this.inquiry = inquiry;
   }

}