/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.List;
import msharpmodel.Contact;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Address {

    private String barCode;
    private String carrierRoute;
    private String cass;
    private String city;
    private String contactId;
    private String coounty;
    private String country;
    private String dpbc2;
    private String id;
    private boolean isActive;
    private String latitude;
    private String line1;
    private String line2;
    private String longitude;
    private String state;
    private String zip;
    private String zip4;
    private List<Contact> contact;

    /**
     * Constructor without parameter.
     * 
     */
    public Address() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Address(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "barCode" attribute.
    *
    * @return The value of the "barCode" attribute.
    */
   public String getBarCode() {
      return barCode;
   }
   /**
    * Returns the value of the "carrierRoute" attribute.
    *
    * @return The value of the "carrierRoute" attribute.
    */
   public String getCarrierRoute() {
      return carrierRoute;
   }
   /**
    * Returns the value of the "cass" attribute.
    *
    * @return The value of the "cass" attribute.
    */
   public String getCass() {
      return cass;
   }
   /**
    * Returns the value of the "city" attribute.
    *
    * @return The value of the "city" attribute.
    */
   public String getCity() {
      return city;
   }
   /**
    * Returns the value of the "contactId" attribute.
    *
    * @return The value of the "contactId" attribute.
    */
   public String getContactId() {
      return contactId;
   }
   /**
    * Returns the value of the "coounty" attribute.
    *
    * @return The value of the "coounty" attribute.
    */
   public String getCoounty() {
      return coounty;
   }
   /**
    * Returns the value of the "country" attribute.
    *
    * @return The value of the "country" attribute.
    */
   public String getCountry() {
      return country;
   }
   /**
    * Returns the value of the "dpbc2" attribute.
    *
    * @return The value of the "dpbc2" attribute.
    */
   public String getDpbc2() {
      return dpbc2;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "latitude" attribute.
    *
    * @return The value of the "latitude" attribute.
    */
   public String getLatitude() {
      return latitude;
   }
   /**
    * Returns the value of the "line1" attribute.
    *
    * @return The value of the "line1" attribute.
    */
   public String getLine1() {
      return line1;
   }
   /**
    * Returns the value of the "line2" attribute.
    *
    * @return The value of the "line2" attribute.
    */
   public String getLine2() {
      return line2;
   }
   /**
    * Returns the value of the "longitude" attribute.
    *
    * @return The value of the "longitude" attribute.
    */
   public String getLongitude() {
      return longitude;
   }
   /**
    * Returns the value of the "state" attribute.
    *
    * @return The value of the "state" attribute.
    */
   public String getState() {
      return state;
   }
   /**
    * Returns the value of the "zip" attribute.
    *
    * @return The value of the "zip" attribute.
    */
   public String getZip() {
      return zip;
   }
   /**
    * Returns the value of the "zip4" attribute.
    *
    * @return The value of the "zip4" attribute.
    */
   public String getZip4() {
      return zip4;
   }
   /**
    * Returns the value of the "contact" attribute.
    *
    * @return The value of the "contact" attribute.
    */
   public List<Contact> getContact() {
      return contact;
   }
   
   /**
    * Sets the value of the "barCode" attribute.
    *
    * @param barCode
    *     The value of the "barCode" attribute.
    */
   public void setBarCode(String barCode) {
      this.barCode = barCode;
   }
   /**
    * Sets the value of the "carrierRoute" attribute.
    *
    * @param carrierRoute
    *     The value of the "carrierRoute" attribute.
    */
   public void setCarrierRoute(String carrierRoute) {
      this.carrierRoute = carrierRoute;
   }
   /**
    * Sets the value of the "cass" attribute.
    *
    * @param cass
    *     The value of the "cass" attribute.
    */
   public void setCass(String cass) {
      this.cass = cass;
   }
   /**
    * Sets the value of the "city" attribute.
    *
    * @param city
    *     The value of the "city" attribute.
    */
   public void setCity(String city) {
      this.city = city;
   }
   /**
    * Sets the value of the "contactId" attribute.
    *
    * @param contactId
    *     The value of the "contactId" attribute.
    */
   public void setContactId(String contactId) {
      this.contactId = contactId;
   }
   /**
    * Sets the value of the "coounty" attribute.
    *
    * @param coounty
    *     The value of the "coounty" attribute.
    */
   public void setCoounty(String coounty) {
      this.coounty = coounty;
   }
   /**
    * Sets the value of the "country" attribute.
    *
    * @param country
    *     The value of the "country" attribute.
    */
   public void setCountry(String country) {
      this.country = country;
   }
   /**
    * Sets the value of the "dpbc2" attribute.
    *
    * @param dpbc2
    *     The value of the "dpbc2" attribute.
    */
   public void setDpbc2(String dpbc2) {
      this.dpbc2 = dpbc2;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "latitude" attribute.
    *
    * @param latitude
    *     The value of the "latitude" attribute.
    */
   public void setLatitude(String latitude) {
      this.latitude = latitude;
   }
   /**
    * Sets the value of the "line1" attribute.
    *
    * @param line1
    *     The value of the "line1" attribute.
    */
   public void setLine1(String line1) {
      this.line1 = line1;
   }
   /**
    * Sets the value of the "line2" attribute.
    *
    * @param line2
    *     The value of the "line2" attribute.
    */
   public void setLine2(String line2) {
      this.line2 = line2;
   }
   /**
    * Sets the value of the "longitude" attribute.
    *
    * @param longitude
    *     The value of the "longitude" attribute.
    */
   public void setLongitude(String longitude) {
      this.longitude = longitude;
   }
   /**
    * Sets the value of the "state" attribute.
    *
    * @param state
    *     The value of the "state" attribute.
    */
   public void setState(String state) {
      this.state = state;
   }
   /**
    * Sets the value of the "zip" attribute.
    *
    * @param zip
    *     The value of the "zip" attribute.
    */
   public void setZip(String zip) {
      this.zip = zip;
   }
   /**
    * Sets the value of the "zip4" attribute.
    *
    * @param zip4
    *     The value of the "zip4" attribute.
    */
   public void setZip4(String zip4) {
      this.zip4 = zip4;
   }
   /**
    * Sets the value of the "contact" attribute.
    *
    * @param contact"
    *     The value of the "contact" attribute.
    */
   public void setContact(List<Contact> contact) {
      this.contact = contact;
   }

}