/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.List;
import msharpmodel.Appointment;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class AppointmentResult {

    private String id;
    private boolean isActive;
    private String name;
    private boolean presentation;
    private boolean sold;
    private List<Appointment> appointment;

    /**
     * Constructor without parameter.
     * 
     */
    public AppointmentResult() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public AppointmentResult(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "presentation" attribute.
    *
    * @return The value of the "presentation" attribute.
    */
   public boolean getPresentation() {
      return presentation;
   }
   /**
    * Returns the value of the "sold" attribute.
    *
    * @return The value of the "sold" attribute.
    */
   public boolean getSold() {
      return sold;
   }
   /**
    * Returns the value of the "appointment" attribute.
    *
    * @return The value of the "appointment" attribute.
    */
   public List<Appointment> getAppointment() {
      return appointment;
   }
   
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "presentation" attribute.
    *
    * @param presentation
    *     The value of the "presentation" attribute.
    */
   public void setPresentation(boolean presentation) {
      this.presentation = presentation;
   }
   /**
    * Sets the value of the "sold" attribute.
    *
    * @param sold
    *     The value of the "sold" attribute.
    */
   public void setSold(boolean sold) {
      this.sold = sold;
   }
   /**
    * Sets the value of the "appointment" attribute.
    *
    * @param appointment"
    *     The value of the "appointment" attribute.
    */
   public void setAppointment(List<Appointment> appointment) {
      this.appointment = appointment;
   }

}