/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Activity;
import msharpmodel.Company;
import msharpmodel.Contact;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class C800responseLead {

    private String activityId;
    private String caller;
    private String callRecordingLink;
    private String callRecordingRawLink;
    private String callTag;
    private String city;
    private String companyId;
    private String contactId;
    private Date createdDateUtc;
    private String date;
    private String dateTimeUtc;
    private String dialed;
    private String duration;
    private String firstName;
    private int id;
    private String lastName;
    private String ringTo;
    private String ringToLabel;
    private String state;
    private String streetAddress;
    private String time;
    private String vendorLeadId;
    private String zip;
    private Activity activity;
    private Company company;
    private Contact contact;

    /**
     * Constructor without parameter.
     * 
     */
    public C800responseLead() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public C800responseLead(int id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "activityId" attribute.
    *
    * @return The value of the "activityId" attribute.
    */
   public String getActivityId() {
      return activityId;
   }
   /**
    * Returns the value of the "caller" attribute.
    *
    * @return The value of the "caller" attribute.
    */
   public String getCaller() {
      return caller;
   }
   /**
    * Returns the value of the "callRecordingLink" attribute.
    *
    * @return The value of the "callRecordingLink" attribute.
    */
   public String getCallRecordingLink() {
      return callRecordingLink;
   }
   /**
    * Returns the value of the "callRecordingRawLink" attribute.
    *
    * @return The value of the "callRecordingRawLink" attribute.
    */
   public String getCallRecordingRawLink() {
      return callRecordingRawLink;
   }
   /**
    * Returns the value of the "callTag" attribute.
    *
    * @return The value of the "callTag" attribute.
    */
   public String getCallTag() {
      return callTag;
   }
   /**
    * Returns the value of the "city" attribute.
    *
    * @return The value of the "city" attribute.
    */
   public String getCity() {
      return city;
   }
   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "contactId" attribute.
    *
    * @return The value of the "contactId" attribute.
    */
   public String getContactId() {
      return contactId;
   }
   /**
    * Returns the value of the "createdDateUtc" attribute.
    *
    * @return The value of the "createdDateUtc" attribute.
    */
   public Date getCreatedDateUtc() {
      return createdDateUtc;
   }
   /**
    * Returns the value of the "date" attribute.
    *
    * @return The value of the "date" attribute.
    */
   public String getDate() {
      return date;
   }
   /**
    * Returns the value of the "dateTimeUtc" attribute.
    *
    * @return The value of the "dateTimeUtc" attribute.
    */
   public String getDateTimeUtc() {
      return dateTimeUtc;
   }
   /**
    * Returns the value of the "dialed" attribute.
    *
    * @return The value of the "dialed" attribute.
    */
   public String getDialed() {
      return dialed;
   }
   /**
    * Returns the value of the "duration" attribute.
    *
    * @return The value of the "duration" attribute.
    */
   public String getDuration() {
      return duration;
   }
   /**
    * Returns the value of the "firstName" attribute.
    *
    * @return The value of the "firstName" attribute.
    */
   public String getFirstName() {
      return firstName;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public int getId() {
      return id;
   }
   /**
    * Returns the value of the "lastName" attribute.
    *
    * @return The value of the "lastName" attribute.
    */
   public String getLastName() {
      return lastName;
   }
   /**
    * Returns the value of the "ringTo" attribute.
    *
    * @return The value of the "ringTo" attribute.
    */
   public String getRingTo() {
      return ringTo;
   }
   /**
    * Returns the value of the "ringToLabel" attribute.
    *
    * @return The value of the "ringToLabel" attribute.
    */
   public String getRingToLabel() {
      return ringToLabel;
   }
   /**
    * Returns the value of the "state" attribute.
    *
    * @return The value of the "state" attribute.
    */
   public String getState() {
      return state;
   }
   /**
    * Returns the value of the "streetAddress" attribute.
    *
    * @return The value of the "streetAddress" attribute.
    */
   public String getStreetAddress() {
      return streetAddress;
   }
   /**
    * Returns the value of the "time" attribute.
    *
    * @return The value of the "time" attribute.
    */
   public String getTime() {
      return time;
   }
   /**
    * Returns the value of the "vendorLeadId" attribute.
    *
    * @return The value of the "vendorLeadId" attribute.
    */
   public String getVendorLeadId() {
      return vendorLeadId;
   }
   /**
    * Returns the value of the "zip" attribute.
    *
    * @return The value of the "zip" attribute.
    */
   public String getZip() {
      return zip;
   }
   /**
    * Returns the value of the "activity" attribute.
    *
    * @return The value of the "activity" attribute.
    */
   public Activity getActivity() {
      return activity;
   }
   
   /**
    * Returns the value of the "company" attribute.
    *
    * @return The value of the "company" attribute.
    */
   public Company getCompany() {
      return company;
   }
   
   /**
    * Returns the value of the "contact" attribute.
    *
    * @return The value of the "contact" attribute.
    */
   public Contact getContact() {
      return contact;
   }
   
   /**
    * Sets the value of the "activityId" attribute.
    *
    * @param activityId
    *     The value of the "activityId" attribute.
    */
   public void setActivityId(String activityId) {
      this.activityId = activityId;
   }
   /**
    * Sets the value of the "caller" attribute.
    *
    * @param caller
    *     The value of the "caller" attribute.
    */
   public void setCaller(String caller) {
      this.caller = caller;
   }
   /**
    * Sets the value of the "callRecordingLink" attribute.
    *
    * @param callRecordingLink
    *     The value of the "callRecordingLink" attribute.
    */
   public void setCallRecordingLink(String callRecordingLink) {
      this.callRecordingLink = callRecordingLink;
   }
   /**
    * Sets the value of the "callRecordingRawLink" attribute.
    *
    * @param callRecordingRawLink
    *     The value of the "callRecordingRawLink" attribute.
    */
   public void setCallRecordingRawLink(String callRecordingRawLink) {
      this.callRecordingRawLink = callRecordingRawLink;
   }
   /**
    * Sets the value of the "callTag" attribute.
    *
    * @param callTag
    *     The value of the "callTag" attribute.
    */
   public void setCallTag(String callTag) {
      this.callTag = callTag;
   }
   /**
    * Sets the value of the "city" attribute.
    *
    * @param city
    *     The value of the "city" attribute.
    */
   public void setCity(String city) {
      this.city = city;
   }
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "contactId" attribute.
    *
    * @param contactId
    *     The value of the "contactId" attribute.
    */
   public void setContactId(String contactId) {
      this.contactId = contactId;
   }
   /**
    * Sets the value of the "createdDateUtc" attribute.
    *
    * @param createdDateUtc
    *     The value of the "createdDateUtc" attribute.
    */
   public void setCreatedDateUtc(Date createdDateUtc) {
      this.createdDateUtc = createdDateUtc;
   }
   /**
    * Sets the value of the "date" attribute.
    *
    * @param date
    *     The value of the "date" attribute.
    */
   public void setDate(String date) {
      this.date = date;
   }
   /**
    * Sets the value of the "dateTimeUtc" attribute.
    *
    * @param dateTimeUtc
    *     The value of the "dateTimeUtc" attribute.
    */
   public void setDateTimeUtc(String dateTimeUtc) {
      this.dateTimeUtc = dateTimeUtc;
   }
   /**
    * Sets the value of the "dialed" attribute.
    *
    * @param dialed
    *     The value of the "dialed" attribute.
    */
   public void setDialed(String dialed) {
      this.dialed = dialed;
   }
   /**
    * Sets the value of the "duration" attribute.
    *
    * @param duration
    *     The value of the "duration" attribute.
    */
   public void setDuration(String duration) {
      this.duration = duration;
   }
   /**
    * Sets the value of the "firstName" attribute.
    *
    * @param firstName
    *     The value of the "firstName" attribute.
    */
   public void setFirstName(String firstName) {
      this.firstName = firstName;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(int id) {
      this.id = id;
   }
   /**
    * Sets the value of the "lastName" attribute.
    *
    * @param lastName
    *     The value of the "lastName" attribute.
    */
   public void setLastName(String lastName) {
      this.lastName = lastName;
   }
   /**
    * Sets the value of the "ringTo" attribute.
    *
    * @param ringTo
    *     The value of the "ringTo" attribute.
    */
   public void setRingTo(String ringTo) {
      this.ringTo = ringTo;
   }
   /**
    * Sets the value of the "ringToLabel" attribute.
    *
    * @param ringToLabel
    *     The value of the "ringToLabel" attribute.
    */
   public void setRingToLabel(String ringToLabel) {
      this.ringToLabel = ringToLabel;
   }
   /**
    * Sets the value of the "state" attribute.
    *
    * @param state
    *     The value of the "state" attribute.
    */
   public void setState(String state) {
      this.state = state;
   }
   /**
    * Sets the value of the "streetAddress" attribute.
    *
    * @param streetAddress
    *     The value of the "streetAddress" attribute.
    */
   public void setStreetAddress(String streetAddress) {
      this.streetAddress = streetAddress;
   }
   /**
    * Sets the value of the "time" attribute.
    *
    * @param time
    *     The value of the "time" attribute.
    */
   public void setTime(String time) {
      this.time = time;
   }
   /**
    * Sets the value of the "vendorLeadId" attribute.
    *
    * @param vendorLeadId
    *     The value of the "vendorLeadId" attribute.
    */
   public void setVendorLeadId(String vendorLeadId) {
      this.vendorLeadId = vendorLeadId;
   }
   /**
    * Sets the value of the "zip" attribute.
    *
    * @param zip
    *     The value of the "zip" attribute.
    */
   public void setZip(String zip) {
      this.zip = zip;
   }
   /**
    * Sets the value of the "activity" attribute.
    *
    * @param activity"
    *     The value of the "activity" attribute.
    */
   public void setActivity(Activity activity) {
      this.activity = activity;
   }

   /**
    * Sets the value of the "company" attribute.
    *
    * @param company"
    *     The value of the "company" attribute.
    */
   public void setCompany(Company company) {
      this.company = company;
   }

   /**
    * Sets the value of the "contact" attribute.
    *
    * @param contact"
    *     The value of the "contact" attribute.
    */
   public void setContact(Contact contact) {
      this.contact = contact;
   }

}