/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.List;
import msharpmodel.ActivityReference;
import msharpmodel.ActivityResult;
import msharpmodel.C800responseLead;
import msharpmodel.Contact;
import msharpmodel.Employee;
import msharpmodel.InquirySourcePrimary;
import msharpmodel.InquirySourceSecondary;
import msharpmodel.InquiryStatus;
import msharpmodel.ProductDetail;
import msharpmodel.ProductType;
import msharpmodel.WorkCrew;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Company {

    private String addressCity;
    private String addressLine1;
    private String addressLine2;
    private String addressState;
    private String addressZip;
    private String contactName;
    private String contactTitle;
    private String email;
    private String fax;
    private String id;
    private String name;
    private int number;
    private String owner;
    private String phone;
    private String timeZone;
    private String website;
    private List<ActivityReference> activityReference;
    private List<ActivityResult> activityResult;
    private List<C800responseLead> c800responseLead;
    private List<Contact> contact;
    private List<Employee> employee;
    private List<InquirySourcePrimary> inquirySourcePrimary;
    private List<InquirySourceSecondary> inquirySourceSecondary;
    private List<InquiryStatus> inquiryStatus;
    private List<ProductDetail> productDetail;
    private List<ProductType> productType;
    private List<WorkCrew> workCrew;

    /**
     * Constructor without parameter.
     * 
     */
    public Company() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Company(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "addressCity" attribute.
    *
    * @return The value of the "addressCity" attribute.
    */
   public String getAddressCity() {
      return addressCity;
   }
   /**
    * Returns the value of the "addressLine1" attribute.
    *
    * @return The value of the "addressLine1" attribute.
    */
   public String getAddressLine1() {
      return addressLine1;
   }
   /**
    * Returns the value of the "addressLine2" attribute.
    *
    * @return The value of the "addressLine2" attribute.
    */
   public String getAddressLine2() {
      return addressLine2;
   }
   /**
    * Returns the value of the "addressState" attribute.
    *
    * @return The value of the "addressState" attribute.
    */
   public String getAddressState() {
      return addressState;
   }
   /**
    * Returns the value of the "addressZip" attribute.
    *
    * @return The value of the "addressZip" attribute.
    */
   public String getAddressZip() {
      return addressZip;
   }
   /**
    * Returns the value of the "contactName" attribute.
    *
    * @return The value of the "contactName" attribute.
    */
   public String getContactName() {
      return contactName;
   }
   /**
    * Returns the value of the "contactTitle" attribute.
    *
    * @return The value of the "contactTitle" attribute.
    */
   public String getContactTitle() {
      return contactTitle;
   }
   /**
    * Returns the value of the "email" attribute.
    *
    * @return The value of the "email" attribute.
    */
   public String getEmail() {
      return email;
   }
   /**
    * Returns the value of the "fax" attribute.
    *
    * @return The value of the "fax" attribute.
    */
   public String getFax() {
      return fax;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "number" attribute.
    *
    * @return The value of the "number" attribute.
    */
   public int getNumber() {
      return number;
   }
   /**
    * Returns the value of the "owner" attribute.
    *
    * @return The value of the "owner" attribute.
    */
   public String getOwner() {
      return owner;
   }
   /**
    * Returns the value of the "phone" attribute.
    *
    * @return The value of the "phone" attribute.
    */
   public String getPhone() {
      return phone;
   }
   /**
    * Returns the value of the "timeZone" attribute.
    *
    * @return The value of the "timeZone" attribute.
    */
   public String getTimeZone() {
      return timeZone;
   }
   /**
    * Returns the value of the "website" attribute.
    *
    * @return The value of the "website" attribute.
    */
   public String getWebsite() {
      return website;
   }
   /**
    * Returns the value of the "activityReference" attribute.
    *
    * @return The value of the "activityReference" attribute.
    */
   public List<ActivityReference> getActivityReference() {
      return activityReference;
   }
   
   /**
    * Returns the value of the "activityResult" attribute.
    *
    * @return The value of the "activityResult" attribute.
    */
   public List<ActivityResult> getActivityResult() {
      return activityResult;
   }
   
   /**
    * Returns the value of the "c800responseLead" attribute.
    *
    * @return The value of the "c800responseLead" attribute.
    */
   public List<C800responseLead> getC800responseLead() {
      return c800responseLead;
   }
   
   /**
    * Returns the value of the "contact" attribute.
    *
    * @return The value of the "contact" attribute.
    */
   public List<Contact> getContact() {
      return contact;
   }
   
   /**
    * Returns the value of the "employee" attribute.
    *
    * @return The value of the "employee" attribute.
    */
   public List<Employee> getEmployee() {
      return employee;
   }
   
   /**
    * Returns the value of the "inquirySourcePrimary" attribute.
    *
    * @return The value of the "inquirySourcePrimary" attribute.
    */
   public List<InquirySourcePrimary> getInquirySourcePrimary() {
      return inquirySourcePrimary;
   }
   
   /**
    * Returns the value of the "inquirySourceSecondary" attribute.
    *
    * @return The value of the "inquirySourceSecondary" attribute.
    */
   public List<InquirySourceSecondary> getInquirySourceSecondary() {
      return inquirySourceSecondary;
   }
   
   /**
    * Returns the value of the "inquiryStatus" attribute.
    *
    * @return The value of the "inquiryStatus" attribute.
    */
   public List<InquiryStatus> getInquiryStatus() {
      return inquiryStatus;
   }
   
   /**
    * Returns the value of the "productDetail" attribute.
    *
    * @return The value of the "productDetail" attribute.
    */
   public List<ProductDetail> getProductDetail() {
      return productDetail;
   }
   
   /**
    * Returns the value of the "productType" attribute.
    *
    * @return The value of the "productType" attribute.
    */
   public List<ProductType> getProductType() {
      return productType;
   }
   
   /**
    * Returns the value of the "workCrew" attribute.
    *
    * @return The value of the "workCrew" attribute.
    */
   public List<WorkCrew> getWorkCrew() {
      return workCrew;
   }
   
   /**
    * Sets the value of the "addressCity" attribute.
    *
    * @param addressCity
    *     The value of the "addressCity" attribute.
    */
   public void setAddressCity(String addressCity) {
      this.addressCity = addressCity;
   }
   /**
    * Sets the value of the "addressLine1" attribute.
    *
    * @param addressLine1
    *     The value of the "addressLine1" attribute.
    */
   public void setAddressLine1(String addressLine1) {
      this.addressLine1 = addressLine1;
   }
   /**
    * Sets the value of the "addressLine2" attribute.
    *
    * @param addressLine2
    *     The value of the "addressLine2" attribute.
    */
   public void setAddressLine2(String addressLine2) {
      this.addressLine2 = addressLine2;
   }
   /**
    * Sets the value of the "addressState" attribute.
    *
    * @param addressState
    *     The value of the "addressState" attribute.
    */
   public void setAddressState(String addressState) {
      this.addressState = addressState;
   }
   /**
    * Sets the value of the "addressZip" attribute.
    *
    * @param addressZip
    *     The value of the "addressZip" attribute.
    */
   public void setAddressZip(String addressZip) {
      this.addressZip = addressZip;
   }
   /**
    * Sets the value of the "contactName" attribute.
    *
    * @param contactName
    *     The value of the "contactName" attribute.
    */
   public void setContactName(String contactName) {
      this.contactName = contactName;
   }
   /**
    * Sets the value of the "contactTitle" attribute.
    *
    * @param contactTitle
    *     The value of the "contactTitle" attribute.
    */
   public void setContactTitle(String contactTitle) {
      this.contactTitle = contactTitle;
   }
   /**
    * Sets the value of the "email" attribute.
    *
    * @param email
    *     The value of the "email" attribute.
    */
   public void setEmail(String email) {
      this.email = email;
   }
   /**
    * Sets the value of the "fax" attribute.
    *
    * @param fax
    *     The value of the "fax" attribute.
    */
   public void setFax(String fax) {
      this.fax = fax;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "number" attribute.
    *
    * @param number
    *     The value of the "number" attribute.
    */
   public void setNumber(int number) {
      this.number = number;
   }
   /**
    * Sets the value of the "owner" attribute.
    *
    * @param owner
    *     The value of the "owner" attribute.
    */
   public void setOwner(String owner) {
      this.owner = owner;
   }
   /**
    * Sets the value of the "phone" attribute.
    *
    * @param phone
    *     The value of the "phone" attribute.
    */
   public void setPhone(String phone) {
      this.phone = phone;
   }
   /**
    * Sets the value of the "timeZone" attribute.
    *
    * @param timeZone
    *     The value of the "timeZone" attribute.
    */
   public void setTimeZone(String timeZone) {
      this.timeZone = timeZone;
   }
   /**
    * Sets the value of the "website" attribute.
    *
    * @param website
    *     The value of the "website" attribute.
    */
   public void setWebsite(String website) {
      this.website = website;
   }
   /**
    * Sets the value of the "activityReference" attribute.
    *
    * @param activityReference"
    *     The value of the "activityReference" attribute.
    */
   public void setActivityReference(List<ActivityReference> activityReference) {
      this.activityReference = activityReference;
   }

   /**
    * Sets the value of the "activityResult" attribute.
    *
    * @param activityResult"
    *     The value of the "activityResult" attribute.
    */
   public void setActivityResult(List<ActivityResult> activityResult) {
      this.activityResult = activityResult;
   }

   /**
    * Sets the value of the "c800responseLead" attribute.
    *
    * @param c800responseLead"
    *     The value of the "c800responseLead" attribute.
    */
   public void setC800responseLead(List<C800responseLead> c800responseLead) {
      this.c800responseLead = c800responseLead;
   }

   /**
    * Sets the value of the "contact" attribute.
    *
    * @param contact"
    *     The value of the "contact" attribute.
    */
   public void setContact(List<Contact> contact) {
      this.contact = contact;
   }

   /**
    * Sets the value of the "employee" attribute.
    *
    * @param employee"
    *     The value of the "employee" attribute.
    */
   public void setEmployee(List<Employee> employee) {
      this.employee = employee;
   }

   /**
    * Sets the value of the "inquirySourcePrimary" attribute.
    *
    * @param inquirySourcePrimary"
    *     The value of the "inquirySourcePrimary" attribute.
    */
   public void setInquirySourcePrimary(List<InquirySourcePrimary> inquirySourcePrimary) {
      this.inquirySourcePrimary = inquirySourcePrimary;
   }

   /**
    * Sets the value of the "inquirySourceSecondary" attribute.
    *
    * @param inquirySourceSecondary"
    *     The value of the "inquirySourceSecondary" attribute.
    */
   public void setInquirySourceSecondary(List<InquirySourceSecondary> inquirySourceSecondary) {
      this.inquirySourceSecondary = inquirySourceSecondary;
   }

   /**
    * Sets the value of the "inquiryStatus" attribute.
    *
    * @param inquiryStatus"
    *     The value of the "inquiryStatus" attribute.
    */
   public void setInquiryStatus(List<InquiryStatus> inquiryStatus) {
      this.inquiryStatus = inquiryStatus;
   }

   /**
    * Sets the value of the "productDetail" attribute.
    *
    * @param productDetail"
    *     The value of the "productDetail" attribute.
    */
   public void setProductDetail(List<ProductDetail> productDetail) {
      this.productDetail = productDetail;
   }

   /**
    * Sets the value of the "productType" attribute.
    *
    * @param productType"
    *     The value of the "productType" attribute.
    */
   public void setProductType(List<ProductType> productType) {
      this.productType = productType;
   }

   /**
    * Sets the value of the "workCrew" attribute.
    *
    * @param workCrew"
    *     The value of the "workCrew" attribute.
    */
   public void setWorkCrew(List<WorkCrew> workCrew) {
      this.workCrew = workCrew;
   }

}