/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import java.util.List;
import msharpmodel.Activity;
import msharpmodel.AdditionalContact;
import msharpmodel.Address;
import msharpmodel.C800responseLead;
import msharpmodel.Company;
import msharpmodel.ContactPhone;
import msharpmodel.ContactType;
import msharpmodel.CustomField;
import msharpmodel.FutureInterest;
import msharpmodel.Inquiry;
import msharpmodel.Job;
import msharpmodel.Note;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Contact {

    private String ageCode;
    private String businessName;
    private String companyId;
    private String contactPhoneId;
    private Date createdDate;
    private Date creationDate;
    private boolean doNotMail;
    private String email1;
    private boolean email1canMail;
    private String email2;
    private boolean email2canMail;
    private String email3;
    private boolean email3canMail;
    private String firstName;
    private boolean hasDncphone;
    private boolean hasDneemail;
    private String id;
    private String incomeCode;
    private boolean isActive;
    private boolean isTagged;
    private String lastName;
    private Date lastUpdate;
    private String lengthOfResidence;
    private String mailMergeName;
    private String maritalStatus;
    private String middleInitial;
    private String primaryAddressId;
    private String qbEditSequence;
    private String qbId;
    private String qbName;
    private boolean qbSyncData;
    private Date qbSyncDate;
    private String reference;
    private String source;
    private String structureAgeCode;
    private String structureValueCode;
    private String styleOfHome;
    private String title;
    private String website1;
    private String website2;
    private String website3;
    private String yearHomeBuilt;
    private List<Activity> activity;
    private List<AdditionalContact> additionalContact;
    private Address address;
    private List<C800responseLead> c800responseLead;
    private Company company;
    private ContactPhone contactPhone;
    private List<ContactType> contactType;
    private List<CustomField> customField;
    private List<FutureInterest> futureInterest;
    private List<Inquiry> inquiry;
    private List<Job> job;
    private List<Note> note;

    /**
     * Constructor without parameter.
     * 
     */
    public Contact() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Contact(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "ageCode" attribute.
    *
    * @return The value of the "ageCode" attribute.
    */
   public String getAgeCode() {
      return ageCode;
   }
   /**
    * Returns the value of the "businessName" attribute.
    *
    * @return The value of the "businessName" attribute.
    */
   public String getBusinessName() {
      return businessName;
   }
   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "contactPhoneId" attribute.
    *
    * @return The value of the "contactPhoneId" attribute.
    */
   public String getContactPhoneId() {
      return contactPhoneId;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "creationDate" attribute.
    *
    * @return The value of the "creationDate" attribute.
    */
   public Date getCreationDate() {
      return creationDate;
   }
   /**
    * Returns the value of the "doNotMail" attribute.
    *
    * @return The value of the "doNotMail" attribute.
    */
   public boolean getDoNotMail() {
      return doNotMail;
   }
   /**
    * Returns the value of the "email1" attribute.
    *
    * @return The value of the "email1" attribute.
    */
   public String getEmail1() {
      return email1;
   }
   /**
    * Returns the value of the "email1canMail" attribute.
    *
    * @return The value of the "email1canMail" attribute.
    */
   public boolean getEmail1canMail() {
      return email1canMail;
   }
   /**
    * Returns the value of the "email2" attribute.
    *
    * @return The value of the "email2" attribute.
    */
   public String getEmail2() {
      return email2;
   }
   /**
    * Returns the value of the "email2canMail" attribute.
    *
    * @return The value of the "email2canMail" attribute.
    */
   public boolean getEmail2canMail() {
      return email2canMail;
   }
   /**
    * Returns the value of the "email3" attribute.
    *
    * @return The value of the "email3" attribute.
    */
   public String getEmail3() {
      return email3;
   }
   /**
    * Returns the value of the "email3canMail" attribute.
    *
    * @return The value of the "email3canMail" attribute.
    */
   public boolean getEmail3canMail() {
      return email3canMail;
   }
   /**
    * Returns the value of the "firstName" attribute.
    *
    * @return The value of the "firstName" attribute.
    */
   public String getFirstName() {
      return firstName;
   }
   /**
    * Returns the value of the "hasDncphone" attribute.
    *
    * @return The value of the "hasDncphone" attribute.
    */
   public boolean getHasDncphone() {
      return hasDncphone;
   }
   /**
    * Returns the value of the "hasDneemail" attribute.
    *
    * @return The value of the "hasDneemail" attribute.
    */
   public boolean getHasDneemail() {
      return hasDneemail;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "incomeCode" attribute.
    *
    * @return The value of the "incomeCode" attribute.
    */
   public String getIncomeCode() {
      return incomeCode;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "isTagged" attribute.
    *
    * @return The value of the "isTagged" attribute.
    */
   public boolean getIsTagged() {
      return isTagged;
   }
   /**
    * Returns the value of the "lastName" attribute.
    *
    * @return The value of the "lastName" attribute.
    */
   public String getLastName() {
      return lastName;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lengthOfResidence" attribute.
    *
    * @return The value of the "lengthOfResidence" attribute.
    */
   public String getLengthOfResidence() {
      return lengthOfResidence;
   }
   /**
    * Returns the value of the "mailMergeName" attribute.
    *
    * @return The value of the "mailMergeName" attribute.
    */
   public String getMailMergeName() {
      return mailMergeName;
   }
   /**
    * Returns the value of the "maritalStatus" attribute.
    *
    * @return The value of the "maritalStatus" attribute.
    */
   public String getMaritalStatus() {
      return maritalStatus;
   }
   /**
    * Returns the value of the "middleInitial" attribute.
    *
    * @return The value of the "middleInitial" attribute.
    */
   public String getMiddleInitial() {
      return middleInitial;
   }
   /**
    * Returns the value of the "primaryAddressId" attribute.
    *
    * @return The value of the "primaryAddressId" attribute.
    */
   public String getPrimaryAddressId() {
      return primaryAddressId;
   }
   /**
    * Returns the value of the "qbEditSequence" attribute.
    *
    * @return The value of the "qbEditSequence" attribute.
    */
   public String getQbEditSequence() {
      return qbEditSequence;
   }
   /**
    * Returns the value of the "qbId" attribute.
    *
    * @return The value of the "qbId" attribute.
    */
   public String getQbId() {
      return qbId;
   }
   /**
    * Returns the value of the "qbName" attribute.
    *
    * @return The value of the "qbName" attribute.
    */
   public String getQbName() {
      return qbName;
   }
   /**
    * Returns the value of the "qbSyncData" attribute.
    *
    * @return The value of the "qbSyncData" attribute.
    */
   public boolean getQbSyncData() {
      return qbSyncData;
   }
   /**
    * Returns the value of the "qbSyncDate" attribute.
    *
    * @return The value of the "qbSyncDate" attribute.
    */
   public Date getQbSyncDate() {
      return qbSyncDate;
   }
   /**
    * Returns the value of the "reference" attribute.
    *
    * @return The value of the "reference" attribute.
    */
   public String getReference() {
      return reference;
   }
   /**
    * Returns the value of the "source" attribute.
    *
    * @return The value of the "source" attribute.
    */
   public String getSource() {
      return source;
   }
   /**
    * Returns the value of the "structureAgeCode" attribute.
    *
    * @return The value of the "structureAgeCode" attribute.
    */
   public String getStructureAgeCode() {
      return structureAgeCode;
   }
   /**
    * Returns the value of the "structureValueCode" attribute.
    *
    * @return The value of the "structureValueCode" attribute.
    */
   public String getStructureValueCode() {
      return structureValueCode;
   }
   /**
    * Returns the value of the "styleOfHome" attribute.
    *
    * @return The value of the "styleOfHome" attribute.
    */
   public String getStyleOfHome() {
      return styleOfHome;
   }
   /**
    * Returns the value of the "title" attribute.
    *
    * @return The value of the "title" attribute.
    */
   public String getTitle() {
      return title;
   }
   /**
    * Returns the value of the "website1" attribute.
    *
    * @return The value of the "website1" attribute.
    */
   public String getWebsite1() {
      return website1;
   }
   /**
    * Returns the value of the "website2" attribute.
    *
    * @return The value of the "website2" attribute.
    */
   public String getWebsite2() {
      return website2;
   }
   /**
    * Returns the value of the "website3" attribute.
    *
    * @return The value of the "website3" attribute.
    */
   public String getWebsite3() {
      return website3;
   }
   /**
    * Returns the value of the "yearHomeBuilt" attribute.
    *
    * @return The value of the "yearHomeBuilt" attribute.
    */
   public String getYearHomeBuilt() {
      return yearHomeBuilt;
   }
   /**
    * Returns the value of the "activity" attribute.
    *
    * @return The value of the "activity" attribute.
    */
   public List<Activity> getActivity() {
      return activity;
   }
   
   /**
    * Returns the value of the "additionalContact" attribute.
    *
    * @return The value of the "additionalContact" attribute.
    */
   public List<AdditionalContact> getAdditionalContact() {
      return additionalContact;
   }
   
   /**
    * Returns the value of the "address" attribute.
    *
    * @return The value of the "address" attribute.
    */
   public Address getAddress() {
      return address;
   }
   
   /**
    * Returns the value of the "c800responseLead" attribute.
    *
    * @return The value of the "c800responseLead" attribute.
    */
   public List<C800responseLead> getC800responseLead() {
      return c800responseLead;
   }
   
   /**
    * Returns the value of the "company" attribute.
    *
    * @return The value of the "company" attribute.
    */
   public Company getCompany() {
      return company;
   }
   
   /**
    * Returns the value of the "contactPhone" attribute.
    *
    * @return The value of the "contactPhone" attribute.
    */
   public ContactPhone getContactPhone() {
      return contactPhone;
   }
   
   /**
    * Returns the value of the "contactType" attribute.
    *
    * @return The value of the "contactType" attribute.
    */
   public List<ContactType> getContactType() {
      return contactType;
   }
   
   /**
    * Returns the value of the "customField" attribute.
    *
    * @return The value of the "customField" attribute.
    */
   public List<CustomField> getCustomField() {
      return customField;
   }
   
   /**
    * Returns the value of the "futureInterest" attribute.
    *
    * @return The value of the "futureInterest" attribute.
    */
   public List<FutureInterest> getFutureInterest() {
      return futureInterest;
   }
   
   /**
    * Returns the value of the "inquiry" attribute.
    *
    * @return The value of the "inquiry" attribute.
    */
   public List<Inquiry> getInquiry() {
      return inquiry;
   }
   
   /**
    * Returns the value of the "job" attribute.
    *
    * @return The value of the "job" attribute.
    */
   public List<Job> getJob() {
      return job;
   }
   
   /**
    * Returns the value of the "note" attribute.
    *
    * @return The value of the "note" attribute.
    */
   public List<Note> getNote() {
      return note;
   }
   
   /**
    * Sets the value of the "ageCode" attribute.
    *
    * @param ageCode
    *     The value of the "ageCode" attribute.
    */
   public void setAgeCode(String ageCode) {
      this.ageCode = ageCode;
   }
   /**
    * Sets the value of the "businessName" attribute.
    *
    * @param businessName
    *     The value of the "businessName" attribute.
    */
   public void setBusinessName(String businessName) {
      this.businessName = businessName;
   }
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "contactPhoneId" attribute.
    *
    * @param contactPhoneId
    *     The value of the "contactPhoneId" attribute.
    */
   public void setContactPhoneId(String contactPhoneId) {
      this.contactPhoneId = contactPhoneId;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "creationDate" attribute.
    *
    * @param creationDate
    *     The value of the "creationDate" attribute.
    */
   public void setCreationDate(Date creationDate) {
      this.creationDate = creationDate;
   }
   /**
    * Sets the value of the "doNotMail" attribute.
    *
    * @param doNotMail
    *     The value of the "doNotMail" attribute.
    */
   public void setDoNotMail(boolean doNotMail) {
      this.doNotMail = doNotMail;
   }
   /**
    * Sets the value of the "email1" attribute.
    *
    * @param email1
    *     The value of the "email1" attribute.
    */
   public void setEmail1(String email1) {
      this.email1 = email1;
   }
   /**
    * Sets the value of the "email1canMail" attribute.
    *
    * @param email1canMail
    *     The value of the "email1canMail" attribute.
    */
   public void setEmail1canMail(boolean email1canMail) {
      this.email1canMail = email1canMail;
   }
   /**
    * Sets the value of the "email2" attribute.
    *
    * @param email2
    *     The value of the "email2" attribute.
    */
   public void setEmail2(String email2) {
      this.email2 = email2;
   }
   /**
    * Sets the value of the "email2canMail" attribute.
    *
    * @param email2canMail
    *     The value of the "email2canMail" attribute.
    */
   public void setEmail2canMail(boolean email2canMail) {
      this.email2canMail = email2canMail;
   }
   /**
    * Sets the value of the "email3" attribute.
    *
    * @param email3
    *     The value of the "email3" attribute.
    */
   public void setEmail3(String email3) {
      this.email3 = email3;
   }
   /**
    * Sets the value of the "email3canMail" attribute.
    *
    * @param email3canMail
    *     The value of the "email3canMail" attribute.
    */
   public void setEmail3canMail(boolean email3canMail) {
      this.email3canMail = email3canMail;
   }
   /**
    * Sets the value of the "firstName" attribute.
    *
    * @param firstName
    *     The value of the "firstName" attribute.
    */
   public void setFirstName(String firstName) {
      this.firstName = firstName;
   }
   /**
    * Sets the value of the "hasDncphone" attribute.
    *
    * @param hasDncphone
    *     The value of the "hasDncphone" attribute.
    */
   public void setHasDncphone(boolean hasDncphone) {
      this.hasDncphone = hasDncphone;
   }
   /**
    * Sets the value of the "hasDneemail" attribute.
    *
    * @param hasDneemail
    *     The value of the "hasDneemail" attribute.
    */
   public void setHasDneemail(boolean hasDneemail) {
      this.hasDneemail = hasDneemail;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "incomeCode" attribute.
    *
    * @param incomeCode
    *     The value of the "incomeCode" attribute.
    */
   public void setIncomeCode(String incomeCode) {
      this.incomeCode = incomeCode;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "isTagged" attribute.
    *
    * @param isTagged
    *     The value of the "isTagged" attribute.
    */
   public void setIsTagged(boolean isTagged) {
      this.isTagged = isTagged;
   }
   /**
    * Sets the value of the "lastName" attribute.
    *
    * @param lastName
    *     The value of the "lastName" attribute.
    */
   public void setLastName(String lastName) {
      this.lastName = lastName;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lengthOfResidence" attribute.
    *
    * @param lengthOfResidence
    *     The value of the "lengthOfResidence" attribute.
    */
   public void setLengthOfResidence(String lengthOfResidence) {
      this.lengthOfResidence = lengthOfResidence;
   }
   /**
    * Sets the value of the "mailMergeName" attribute.
    *
    * @param mailMergeName
    *     The value of the "mailMergeName" attribute.
    */
   public void setMailMergeName(String mailMergeName) {
      this.mailMergeName = mailMergeName;
   }
   /**
    * Sets the value of the "maritalStatus" attribute.
    *
    * @param maritalStatus
    *     The value of the "maritalStatus" attribute.
    */
   public void setMaritalStatus(String maritalStatus) {
      this.maritalStatus = maritalStatus;
   }
   /**
    * Sets the value of the "middleInitial" attribute.
    *
    * @param middleInitial
    *     The value of the "middleInitial" attribute.
    */
   public void setMiddleInitial(String middleInitial) {
      this.middleInitial = middleInitial;
   }
   /**
    * Sets the value of the "primaryAddressId" attribute.
    *
    * @param primaryAddressId
    *     The value of the "primaryAddressId" attribute.
    */
   public void setPrimaryAddressId(String primaryAddressId) {
      this.primaryAddressId = primaryAddressId;
   }
   /**
    * Sets the value of the "qbEditSequence" attribute.
    *
    * @param qbEditSequence
    *     The value of the "qbEditSequence" attribute.
    */
   public void setQbEditSequence(String qbEditSequence) {
      this.qbEditSequence = qbEditSequence;
   }
   /**
    * Sets the value of the "qbId" attribute.
    *
    * @param qbId
    *     The value of the "qbId" attribute.
    */
   public void setQbId(String qbId) {
      this.qbId = qbId;
   }
   /**
    * Sets the value of the "qbName" attribute.
    *
    * @param qbName
    *     The value of the "qbName" attribute.
    */
   public void setQbName(String qbName) {
      this.qbName = qbName;
   }
   /**
    * Sets the value of the "qbSyncData" attribute.
    *
    * @param qbSyncData
    *     The value of the "qbSyncData" attribute.
    */
   public void setQbSyncData(boolean qbSyncData) {
      this.qbSyncData = qbSyncData;
   }
   /**
    * Sets the value of the "qbSyncDate" attribute.
    *
    * @param qbSyncDate
    *     The value of the "qbSyncDate" attribute.
    */
   public void setQbSyncDate(Date qbSyncDate) {
      this.qbSyncDate = qbSyncDate;
   }
   /**
    * Sets the value of the "reference" attribute.
    *
    * @param reference
    *     The value of the "reference" attribute.
    */
   public void setReference(String reference) {
      this.reference = reference;
   }
   /**
    * Sets the value of the "source" attribute.
    *
    * @param source
    *     The value of the "source" attribute.
    */
   public void setSource(String source) {
      this.source = source;
   }
   /**
    * Sets the value of the "structureAgeCode" attribute.
    *
    * @param structureAgeCode
    *     The value of the "structureAgeCode" attribute.
    */
   public void setStructureAgeCode(String structureAgeCode) {
      this.structureAgeCode = structureAgeCode;
   }
   /**
    * Sets the value of the "structureValueCode" attribute.
    *
    * @param structureValueCode
    *     The value of the "structureValueCode" attribute.
    */
   public void setStructureValueCode(String structureValueCode) {
      this.structureValueCode = structureValueCode;
   }
   /**
    * Sets the value of the "styleOfHome" attribute.
    *
    * @param styleOfHome
    *     The value of the "styleOfHome" attribute.
    */
   public void setStyleOfHome(String styleOfHome) {
      this.styleOfHome = styleOfHome;
   }
   /**
    * Sets the value of the "title" attribute.
    *
    * @param title
    *     The value of the "title" attribute.
    */
   public void setTitle(String title) {
      this.title = title;
   }
   /**
    * Sets the value of the "website1" attribute.
    *
    * @param website1
    *     The value of the "website1" attribute.
    */
   public void setWebsite1(String website1) {
      this.website1 = website1;
   }
   /**
    * Sets the value of the "website2" attribute.
    *
    * @param website2
    *     The value of the "website2" attribute.
    */
   public void setWebsite2(String website2) {
      this.website2 = website2;
   }
   /**
    * Sets the value of the "website3" attribute.
    *
    * @param website3
    *     The value of the "website3" attribute.
    */
   public void setWebsite3(String website3) {
      this.website3 = website3;
   }
   /**
    * Sets the value of the "yearHomeBuilt" attribute.
    *
    * @param yearHomeBuilt
    *     The value of the "yearHomeBuilt" attribute.
    */
   public void setYearHomeBuilt(String yearHomeBuilt) {
      this.yearHomeBuilt = yearHomeBuilt;
   }
   /**
    * Sets the value of the "activity" attribute.
    *
    * @param activity"
    *     The value of the "activity" attribute.
    */
   public void setActivity(List<Activity> activity) {
      this.activity = activity;
   }

   /**
    * Sets the value of the "additionalContact" attribute.
    *
    * @param additionalContact"
    *     The value of the "additionalContact" attribute.
    */
   public void setAdditionalContact(List<AdditionalContact> additionalContact) {
      this.additionalContact = additionalContact;
   }

   /**
    * Sets the value of the "address" attribute.
    *
    * @param address"
    *     The value of the "address" attribute.
    */
   public void setAddress(Address address) {
      this.address = address;
   }

   /**
    * Sets the value of the "c800responseLead" attribute.
    *
    * @param c800responseLead"
    *     The value of the "c800responseLead" attribute.
    */
   public void setC800responseLead(List<C800responseLead> c800responseLead) {
      this.c800responseLead = c800responseLead;
   }

   /**
    * Sets the value of the "company" attribute.
    *
    * @param company"
    *     The value of the "company" attribute.
    */
   public void setCompany(Company company) {
      this.company = company;
   }

   /**
    * Sets the value of the "contactPhone" attribute.
    *
    * @param contactPhone"
    *     The value of the "contactPhone" attribute.
    */
   public void setContactPhone(ContactPhone contactPhone) {
      this.contactPhone = contactPhone;
   }

   /**
    * Sets the value of the "contactType" attribute.
    *
    * @param contactType"
    *     The value of the "contactType" attribute.
    */
   public void setContactType(List<ContactType> contactType) {
      this.contactType = contactType;
   }

   /**
    * Sets the value of the "customField" attribute.
    *
    * @param customField"
    *     The value of the "customField" attribute.
    */
   public void setCustomField(List<CustomField> customField) {
      this.customField = customField;
   }

   /**
    * Sets the value of the "futureInterest" attribute.
    *
    * @param futureInterest"
    *     The value of the "futureInterest" attribute.
    */
   public void setFutureInterest(List<FutureInterest> futureInterest) {
      this.futureInterest = futureInterest;
   }

   /**
    * Sets the value of the "inquiry" attribute.
    *
    * @param inquiry"
    *     The value of the "inquiry" attribute.
    */
   public void setInquiry(List<Inquiry> inquiry) {
      this.inquiry = inquiry;
   }

   /**
    * Sets the value of the "job" attribute.
    *
    * @param job"
    *     The value of the "job" attribute.
    */
   public void setJob(List<Job> job) {
      this.job = job;
   }

   /**
    * Sets the value of the "note" attribute.
    *
    * @param note"
    *     The value of the "note" attribute.
    */
   public void setNote(List<Note> note) {
      this.note = note;
   }

}