/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import msharpmodel.Contact;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class ContactPhone {

    private String assistantPhone;
    private String cellPhone;
    private String cellPhone2;
    private String companyFax;
    private String companyPhone;
    private String contactId;
    private String homeFax;
    private String homePhone;
    private String homePhone2;
    private String otherPhone;
    private String otherPhone2;
    private String pager;
    private String workFax;
    private String workPhone;
    private String workPhone2;
    private Contact contact;

    /**
     * Constructor without parameter.
     * 
     */
    public ContactPhone() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public ContactPhone(String contactId) {
        this();
        this.contactId = contactId;
    }

   /**
    * Returns the value of the "assistantPhone" attribute.
    *
    * @return The value of the "assistantPhone" attribute.
    */
   public String getAssistantPhone() {
      return assistantPhone;
   }
   /**
    * Returns the value of the "cellPhone" attribute.
    *
    * @return The value of the "cellPhone" attribute.
    */
   public String getCellPhone() {
      return cellPhone;
   }
   /**
    * Returns the value of the "cellPhone2" attribute.
    *
    * @return The value of the "cellPhone2" attribute.
    */
   public String getCellPhone2() {
      return cellPhone2;
   }
   /**
    * Returns the value of the "companyFax" attribute.
    *
    * @return The value of the "companyFax" attribute.
    */
   public String getCompanyFax() {
      return companyFax;
   }
   /**
    * Returns the value of the "companyPhone" attribute.
    *
    * @return The value of the "companyPhone" attribute.
    */
   public String getCompanyPhone() {
      return companyPhone;
   }
   /**
    * Returns the value of the "contactId" attribute.
    *
    * @return The value of the "contactId" attribute.
    */
   public String getContactId() {
      return contactId;
   }
   /**
    * Returns the value of the "homeFax" attribute.
    *
    * @return The value of the "homeFax" attribute.
    */
   public String getHomeFax() {
      return homeFax;
   }
   /**
    * Returns the value of the "homePhone" attribute.
    *
    * @return The value of the "homePhone" attribute.
    */
   public String getHomePhone() {
      return homePhone;
   }
   /**
    * Returns the value of the "homePhone2" attribute.
    *
    * @return The value of the "homePhone2" attribute.
    */
   public String getHomePhone2() {
      return homePhone2;
   }
   /**
    * Returns the value of the "otherPhone" attribute.
    *
    * @return The value of the "otherPhone" attribute.
    */
   public String getOtherPhone() {
      return otherPhone;
   }
   /**
    * Returns the value of the "otherPhone2" attribute.
    *
    * @return The value of the "otherPhone2" attribute.
    */
   public String getOtherPhone2() {
      return otherPhone2;
   }
   /**
    * Returns the value of the "pager" attribute.
    *
    * @return The value of the "pager" attribute.
    */
   public String getPager() {
      return pager;
   }
   /**
    * Returns the value of the "workFax" attribute.
    *
    * @return The value of the "workFax" attribute.
    */
   public String getWorkFax() {
      return workFax;
   }
   /**
    * Returns the value of the "workPhone" attribute.
    *
    * @return The value of the "workPhone" attribute.
    */
   public String getWorkPhone() {
      return workPhone;
   }
   /**
    * Returns the value of the "workPhone2" attribute.
    *
    * @return The value of the "workPhone2" attribute.
    */
   public String getWorkPhone2() {
      return workPhone2;
   }
   /**
    * Returns the value of the "contact" attribute.
    *
    * @return The value of the "contact" attribute.
    */
   public Contact getContact() {
      return contact;
   }
   
   /**
    * Sets the value of the "assistantPhone" attribute.
    *
    * @param assistantPhone
    *     The value of the "assistantPhone" attribute.
    */
   public void setAssistantPhone(String assistantPhone) {
      this.assistantPhone = assistantPhone;
   }
   /**
    * Sets the value of the "cellPhone" attribute.
    *
    * @param cellPhone
    *     The value of the "cellPhone" attribute.
    */
   public void setCellPhone(String cellPhone) {
      this.cellPhone = cellPhone;
   }
   /**
    * Sets the value of the "cellPhone2" attribute.
    *
    * @param cellPhone2
    *     The value of the "cellPhone2" attribute.
    */
   public void setCellPhone2(String cellPhone2) {
      this.cellPhone2 = cellPhone2;
   }
   /**
    * Sets the value of the "companyFax" attribute.
    *
    * @param companyFax
    *     The value of the "companyFax" attribute.
    */
   public void setCompanyFax(String companyFax) {
      this.companyFax = companyFax;
   }
   /**
    * Sets the value of the "companyPhone" attribute.
    *
    * @param companyPhone
    *     The value of the "companyPhone" attribute.
    */
   public void setCompanyPhone(String companyPhone) {
      this.companyPhone = companyPhone;
   }
   /**
    * Sets the value of the "contactId" attribute.
    *
    * @param contactId
    *     The value of the "contactId" attribute.
    */
   public void setContactId(String contactId) {
      this.contactId = contactId;
   }
   /**
    * Sets the value of the "homeFax" attribute.
    *
    * @param homeFax
    *     The value of the "homeFax" attribute.
    */
   public void setHomeFax(String homeFax) {
      this.homeFax = homeFax;
   }
   /**
    * Sets the value of the "homePhone" attribute.
    *
    * @param homePhone
    *     The value of the "homePhone" attribute.
    */
   public void setHomePhone(String homePhone) {
      this.homePhone = homePhone;
   }
   /**
    * Sets the value of the "homePhone2" attribute.
    *
    * @param homePhone2
    *     The value of the "homePhone2" attribute.
    */
   public void setHomePhone2(String homePhone2) {
      this.homePhone2 = homePhone2;
   }
   /**
    * Sets the value of the "otherPhone" attribute.
    *
    * @param otherPhone
    *     The value of the "otherPhone" attribute.
    */
   public void setOtherPhone(String otherPhone) {
      this.otherPhone = otherPhone;
   }
   /**
    * Sets the value of the "otherPhone2" attribute.
    *
    * @param otherPhone2
    *     The value of the "otherPhone2" attribute.
    */
   public void setOtherPhone2(String otherPhone2) {
      this.otherPhone2 = otherPhone2;
   }
   /**
    * Sets the value of the "pager" attribute.
    *
    * @param pager
    *     The value of the "pager" attribute.
    */
   public void setPager(String pager) {
      this.pager = pager;
   }
   /**
    * Sets the value of the "workFax" attribute.
    *
    * @param workFax
    *     The value of the "workFax" attribute.
    */
   public void setWorkFax(String workFax) {
      this.workFax = workFax;
   }
   /**
    * Sets the value of the "workPhone" attribute.
    *
    * @param workPhone
    *     The value of the "workPhone" attribute.
    */
   public void setWorkPhone(String workPhone) {
      this.workPhone = workPhone;
   }
   /**
    * Sets the value of the "workPhone2" attribute.
    *
    * @param workPhone2
    *     The value of the "workPhone2" attribute.
    */
   public void setWorkPhone2(String workPhone2) {
      this.workPhone2 = workPhone2;
   }
   /**
    * Sets the value of the "contact" attribute.
    *
    * @param contact"
    *     The value of the "contact" attribute.
    */
   public void setContact(Contact contact) {
      this.contact = contact;
   }

}