/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import msharpmodel.Employee;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class EmployeeInfo {

    private String emailAddress;
    private String employeeId;
    private String id;
    private String userName;
    private Employee employee;

    /**
     * Constructor without parameter.
     * 
     */
    public EmployeeInfo() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public EmployeeInfo(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "emailAddress" attribute.
    *
    * @return The value of the "emailAddress" attribute.
    */
   public String getEmailAddress() {
      return emailAddress;
   }
   /**
    * Returns the value of the "employeeId" attribute.
    *
    * @return The value of the "employeeId" attribute.
    */
   public String getEmployeeId() {
      return employeeId;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "userName" attribute.
    *
    * @return The value of the "userName" attribute.
    */
   public String getUserName() {
      return userName;
   }
   /**
    * Returns the value of the "employee" attribute.
    *
    * @return The value of the "employee" attribute.
    */
   public Employee getEmployee() {
      return employee;
   }
   
   /**
    * Sets the value of the "emailAddress" attribute.
    *
    * @param emailAddress
    *     The value of the "emailAddress" attribute.
    */
   public void setEmailAddress(String emailAddress) {
      this.emailAddress = emailAddress;
   }
   /**
    * Sets the value of the "employeeId" attribute.
    *
    * @param employeeId
    *     The value of the "employeeId" attribute.
    */
   public void setEmployeeId(String employeeId) {
      this.employeeId = employeeId;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "userName" attribute.
    *
    * @param userName
    *     The value of the "userName" attribute.
    */
   public void setUserName(String userName) {
      this.userName = userName;
   }
   /**
    * Sets the value of the "employee" attribute.
    *
    * @param employee"
    *     The value of the "employee" attribute.
    */
   public void setEmployee(Employee employee) {
      this.employee = employee;
   }

}