/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Contact;
import msharpmodel.ProductDetail;
import msharpmodel.ProductType;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class FutureInterest {

    private String contactId;
    private String createdBy;
    private Date createdDate;
    private String id;
    private Date interestDate;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String productDetailId;
    private String productTypeId;
    private Contact contact;
    private ProductDetail productDetail;
    private ProductType productType;

    /**
     * Constructor without parameter.
     * 
     */
    public FutureInterest() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public FutureInterest(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "contactId" attribute.
    *
    * @return The value of the "contactId" attribute.
    */
   public String getContactId() {
      return contactId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "interestDate" attribute.
    *
    * @return The value of the "interestDate" attribute.
    */
   public Date getInterestDate() {
      return interestDate;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "productDetailId" attribute.
    *
    * @return The value of the "productDetailId" attribute.
    */
   public String getProductDetailId() {
      return productDetailId;
   }
   /**
    * Returns the value of the "productTypeId" attribute.
    *
    * @return The value of the "productTypeId" attribute.
    */
   public String getProductTypeId() {
      return productTypeId;
   }
   /**
    * Returns the value of the "contact" attribute.
    *
    * @return The value of the "contact" attribute.
    */
   public Contact getContact() {
      return contact;
   }
   
   /**
    * Returns the value of the "productDetail" attribute.
    *
    * @return The value of the "productDetail" attribute.
    */
   public ProductDetail getProductDetail() {
      return productDetail;
   }
   
   /**
    * Returns the value of the "productType" attribute.
    *
    * @return The value of the "productType" attribute.
    */
   public ProductType getProductType() {
      return productType;
   }
   
   /**
    * Sets the value of the "contactId" attribute.
    *
    * @param contactId
    *     The value of the "contactId" attribute.
    */
   public void setContactId(String contactId) {
      this.contactId = contactId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "interestDate" attribute.
    *
    * @param interestDate
    *     The value of the "interestDate" attribute.
    */
   public void setInterestDate(Date interestDate) {
      this.interestDate = interestDate;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "productDetailId" attribute.
    *
    * @param productDetailId
    *     The value of the "productDetailId" attribute.
    */
   public void setProductDetailId(String productDetailId) {
      this.productDetailId = productDetailId;
   }
   /**
    * Sets the value of the "productTypeId" attribute.
    *
    * @param productTypeId
    *     The value of the "productTypeId" attribute.
    */
   public void setProductTypeId(String productTypeId) {
      this.productTypeId = productTypeId;
   }
   /**
    * Sets the value of the "contact" attribute.
    *
    * @param contact"
    *     The value of the "contact" attribute.
    */
   public void setContact(Contact contact) {
      this.contact = contact;
   }

   /**
    * Sets the value of the "productDetail" attribute.
    *
    * @param productDetail"
    *     The value of the "productDetail" attribute.
    */
   public void setProductDetail(ProductDetail productDetail) {
      this.productDetail = productDetail;
   }

   /**
    * Sets the value of the "productType" attribute.
    *
    * @param productType"
    *     The value of the "productType" attribute.
    */
   public void setProductType(ProductType productType) {
      this.productType = productType;
   }

}