/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import java.util.List;
import msharpmodel.Activity;
import msharpmodel.Appointment;
import msharpmodel.Contact;
import msharpmodel.Employee;
import msharpmodel.InquirySourcePrimary;
import msharpmodel.InquirySourceSecondary;
import msharpmodel.InquiryStatus;
import msharpmodel.LeadPaint;
import msharpmodel.ProductInterest;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Inquiry {

    private String canvasserId;
    private String contactId;
    private String createdBy;
    private Date createdDate;
    private Date creationDate;
    private String description;
    private String division;
    private String id;
    private Date inquiryDate;
    private String inquirySourcePrimaryId;
    private String inquirySourceSecondaryId;
    private int inquiryStatusId;
    private boolean isActive;
    private String jobSiteAddressLine1;
    private String jobSiteAddressLine2;
    private String jobSiteCity;
    private String jobSiteDirections;
    private String jobSiteState;
    private String jobSiteZip;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String note;
    private String promoterId;
    private String setById;
    private Date setDate;
    private String telemarketerId;
    private List<Activity> activity;
    private List<Appointment> appointment;
    private Employee canvasser;
    private Contact contact;
    private InquirySourcePrimary inquirySourcePrimary;
    private InquirySourceSecondary inquirySourceSecondary;
    private InquiryStatus inquiryStatus;
    private List<LeadPaint> leadPaint;
    private List<ProductInterest> productInterest;
    private Employee promoter;
    private Employee setBy;
    private Employee telemarketer;

    /**
     * Constructor without parameter.
     * 
     */
    public Inquiry() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Inquiry(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "canvasserId" attribute.
    *
    * @return The value of the "canvasserId" attribute.
    */
   public String getCanvasserId() {
      return canvasserId;
   }
   /**
    * Returns the value of the "contactId" attribute.
    *
    * @return The value of the "contactId" attribute.
    */
   public String getContactId() {
      return contactId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "creationDate" attribute.
    *
    * @return The value of the "creationDate" attribute.
    */
   public Date getCreationDate() {
      return creationDate;
   }
   /**
    * Returns the value of the "description" attribute.
    *
    * @return The value of the "description" attribute.
    */
   public String getDescription() {
      return description;
   }
   /**
    * Returns the value of the "division" attribute.
    *
    * @return The value of the "division" attribute.
    */
   public String getDivision() {
      return division;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "inquiryDate" attribute.
    *
    * @return The value of the "inquiryDate" attribute.
    */
   public Date getInquiryDate() {
      return inquiryDate;
   }
   /**
    * Returns the value of the "inquirySourcePrimaryId" attribute.
    *
    * @return The value of the "inquirySourcePrimaryId" attribute.
    */
   public String getInquirySourcePrimaryId() {
      return inquirySourcePrimaryId;
   }
   /**
    * Returns the value of the "inquirySourceSecondaryId" attribute.
    *
    * @return The value of the "inquirySourceSecondaryId" attribute.
    */
   public String getInquirySourceSecondaryId() {
      return inquirySourceSecondaryId;
   }
   /**
    * Returns the value of the "inquiryStatusId" attribute.
    *
    * @return The value of the "inquiryStatusId" attribute.
    */
   public int getInquiryStatusId() {
      return inquiryStatusId;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "jobSiteAddressLine1" attribute.
    *
    * @return The value of the "jobSiteAddressLine1" attribute.
    */
   public String getJobSiteAddressLine1() {
      return jobSiteAddressLine1;
   }
   /**
    * Returns the value of the "jobSiteAddressLine2" attribute.
    *
    * @return The value of the "jobSiteAddressLine2" attribute.
    */
   public String getJobSiteAddressLine2() {
      return jobSiteAddressLine2;
   }
   /**
    * Returns the value of the "jobSiteCity" attribute.
    *
    * @return The value of the "jobSiteCity" attribute.
    */
   public String getJobSiteCity() {
      return jobSiteCity;
   }
   /**
    * Returns the value of the "jobSiteDirections" attribute.
    *
    * @return The value of the "jobSiteDirections" attribute.
    */
   public String getJobSiteDirections() {
      return jobSiteDirections;
   }
   /**
    * Returns the value of the "jobSiteState" attribute.
    *
    * @return The value of the "jobSiteState" attribute.
    */
   public String getJobSiteState() {
      return jobSiteState;
   }
   /**
    * Returns the value of the "jobSiteZip" attribute.
    *
    * @return The value of the "jobSiteZip" attribute.
    */
   public String getJobSiteZip() {
      return jobSiteZip;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "note" attribute.
    *
    * @return The value of the "note" attribute.
    */
   public String getNote() {
      return note;
   }
   /**
    * Returns the value of the "promoterId" attribute.
    *
    * @return The value of the "promoterId" attribute.
    */
   public String getPromoterId() {
      return promoterId;
   }
   /**
    * Returns the value of the "setById" attribute.
    *
    * @return The value of the "setById" attribute.
    */
   public String getSetById() {
      return setById;
   }
   /**
    * Returns the value of the "setDate" attribute.
    *
    * @return The value of the "setDate" attribute.
    */
   public Date getSetDate() {
      return setDate;
   }
   /**
    * Returns the value of the "telemarketerId" attribute.
    *
    * @return The value of the "telemarketerId" attribute.
    */
   public String getTelemarketerId() {
      return telemarketerId;
   }
   /**
    * Returns the value of the "activity" attribute.
    *
    * @return The value of the "activity" attribute.
    */
   public List<Activity> getActivity() {
      return activity;
   }
   
   /**
    * Returns the value of the "appointment" attribute.
    *
    * @return The value of the "appointment" attribute.
    */
   public List<Appointment> getAppointment() {
      return appointment;
   }
   
   /**
    * Returns the value of the "canvasser" attribute.
    *
    * @return The value of the "canvasser" attribute.
    */
   public Employee getCanvasser() {
      return canvasser;
   }
   
   /**
    * Returns the value of the "contact" attribute.
    *
    * @return The value of the "contact" attribute.
    */
   public Contact getContact() {
      return contact;
   }
   
   /**
    * Returns the value of the "inquirySourcePrimary" attribute.
    *
    * @return The value of the "inquirySourcePrimary" attribute.
    */
   public InquirySourcePrimary getInquirySourcePrimary() {
      return inquirySourcePrimary;
   }
   
   /**
    * Returns the value of the "inquirySourceSecondary" attribute.
    *
    * @return The value of the "inquirySourceSecondary" attribute.
    */
   public InquirySourceSecondary getInquirySourceSecondary() {
      return inquirySourceSecondary;
   }
   
   /**
    * Returns the value of the "inquiryStatus" attribute.
    *
    * @return The value of the "inquiryStatus" attribute.
    */
   public InquiryStatus getInquiryStatus() {
      return inquiryStatus;
   }
   
   /**
    * Returns the value of the "leadPaint" attribute.
    *
    * @return The value of the "leadPaint" attribute.
    */
   public List<LeadPaint> getLeadPaint() {
      return leadPaint;
   }
   
   /**
    * Returns the value of the "productInterest" attribute.
    *
    * @return The value of the "productInterest" attribute.
    */
   public List<ProductInterest> getProductInterest() {
      return productInterest;
   }
   
   /**
    * Returns the value of the "promoter" attribute.
    *
    * @return The value of the "promoter" attribute.
    */
   public Employee getPromoter() {
      return promoter;
   }
   
   /**
    * Returns the value of the "setBy" attribute.
    *
    * @return The value of the "setBy" attribute.
    */
   public Employee getSetBy() {
      return setBy;
   }
   
   /**
    * Returns the value of the "telemarketer" attribute.
    *
    * @return The value of the "telemarketer" attribute.
    */
   public Employee getTelemarketer() {
      return telemarketer;
   }
   
   /**
    * Sets the value of the "canvasserId" attribute.
    *
    * @param canvasserId
    *     The value of the "canvasserId" attribute.
    */
   public void setCanvasserId(String canvasserId) {
      this.canvasserId = canvasserId;
   }
   /**
    * Sets the value of the "contactId" attribute.
    *
    * @param contactId
    *     The value of the "contactId" attribute.
    */
   public void setContactId(String contactId) {
      this.contactId = contactId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "creationDate" attribute.
    *
    * @param creationDate
    *     The value of the "creationDate" attribute.
    */
   public void setCreationDate(Date creationDate) {
      this.creationDate = creationDate;
   }
   /**
    * Sets the value of the "description" attribute.
    *
    * @param description
    *     The value of the "description" attribute.
    */
   public void setDescription(String description) {
      this.description = description;
   }
   /**
    * Sets the value of the "division" attribute.
    *
    * @param division
    *     The value of the "division" attribute.
    */
   public void setDivision(String division) {
      this.division = division;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "inquiryDate" attribute.
    *
    * @param inquiryDate
    *     The value of the "inquiryDate" attribute.
    */
   public void setInquiryDate(Date inquiryDate) {
      this.inquiryDate = inquiryDate;
   }
   /**
    * Sets the value of the "inquirySourcePrimaryId" attribute.
    *
    * @param inquirySourcePrimaryId
    *     The value of the "inquirySourcePrimaryId" attribute.
    */
   public void setInquirySourcePrimaryId(String inquirySourcePrimaryId) {
      this.inquirySourcePrimaryId = inquirySourcePrimaryId;
   }
   /**
    * Sets the value of the "inquirySourceSecondaryId" attribute.
    *
    * @param inquirySourceSecondaryId
    *     The value of the "inquirySourceSecondaryId" attribute.
    */
   public void setInquirySourceSecondaryId(String inquirySourceSecondaryId) {
      this.inquirySourceSecondaryId = inquirySourceSecondaryId;
   }
   /**
    * Sets the value of the "inquiryStatusId" attribute.
    *
    * @param inquiryStatusId
    *     The value of the "inquiryStatusId" attribute.
    */
   public void setInquiryStatusId(int inquiryStatusId) {
      this.inquiryStatusId = inquiryStatusId;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "jobSiteAddressLine1" attribute.
    *
    * @param jobSiteAddressLine1
    *     The value of the "jobSiteAddressLine1" attribute.
    */
   public void setJobSiteAddressLine1(String jobSiteAddressLine1) {
      this.jobSiteAddressLine1 = jobSiteAddressLine1;
   }
   /**
    * Sets the value of the "jobSiteAddressLine2" attribute.
    *
    * @param jobSiteAddressLine2
    *     The value of the "jobSiteAddressLine2" attribute.
    */
   public void setJobSiteAddressLine2(String jobSiteAddressLine2) {
      this.jobSiteAddressLine2 = jobSiteAddressLine2;
   }
   /**
    * Sets the value of the "jobSiteCity" attribute.
    *
    * @param jobSiteCity
    *     The value of the "jobSiteCity" attribute.
    */
   public void setJobSiteCity(String jobSiteCity) {
      this.jobSiteCity = jobSiteCity;
   }
   /**
    * Sets the value of the "jobSiteDirections" attribute.
    *
    * @param jobSiteDirections
    *     The value of the "jobSiteDirections" attribute.
    */
   public void setJobSiteDirections(String jobSiteDirections) {
      this.jobSiteDirections = jobSiteDirections;
   }
   /**
    * Sets the value of the "jobSiteState" attribute.
    *
    * @param jobSiteState
    *     The value of the "jobSiteState" attribute.
    */
   public void setJobSiteState(String jobSiteState) {
      this.jobSiteState = jobSiteState;
   }
   /**
    * Sets the value of the "jobSiteZip" attribute.
    *
    * @param jobSiteZip
    *     The value of the "jobSiteZip" attribute.
    */
   public void setJobSiteZip(String jobSiteZip) {
      this.jobSiteZip = jobSiteZip;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "note" attribute.
    *
    * @param note
    *     The value of the "note" attribute.
    */
   public void setNote(String note) {
      this.note = note;
   }
   /**
    * Sets the value of the "promoterId" attribute.
    *
    * @param promoterId
    *     The value of the "promoterId" attribute.
    */
   public void setPromoterId(String promoterId) {
      this.promoterId = promoterId;
   }
   /**
    * Sets the value of the "setById" attribute.
    *
    * @param setById
    *     The value of the "setById" attribute.
    */
   public void setSetById(String setById) {
      this.setById = setById;
   }
   /**
    * Sets the value of the "setDate" attribute.
    *
    * @param setDate
    *     The value of the "setDate" attribute.
    */
   public void setSetDate(Date setDate) {
      this.setDate = setDate;
   }
   /**
    * Sets the value of the "telemarketerId" attribute.
    *
    * @param telemarketerId
    *     The value of the "telemarketerId" attribute.
    */
   public void setTelemarketerId(String telemarketerId) {
      this.telemarketerId = telemarketerId;
   }
   /**
    * Sets the value of the "activity" attribute.
    *
    * @param activity"
    *     The value of the "activity" attribute.
    */
   public void setActivity(List<Activity> activity) {
      this.activity = activity;
   }

   /**
    * Sets the value of the "appointment" attribute.
    *
    * @param appointment"
    *     The value of the "appointment" attribute.
    */
   public void setAppointment(List<Appointment> appointment) {
      this.appointment = appointment;
   }

   /**
    * Sets the value of the "canvasser" attribute.
    *
    * @param canvasser"
    *     The value of the "canvasser" attribute.
    */
   public void setCanvasser(Employee canvasser) {
      this.canvasser = canvasser;
   }

   /**
    * Sets the value of the "contact" attribute.
    *
    * @param contact"
    *     The value of the "contact" attribute.
    */
   public void setContact(Contact contact) {
      this.contact = contact;
   }

   /**
    * Sets the value of the "inquirySourcePrimary" attribute.
    *
    * @param inquirySourcePrimary"
    *     The value of the "inquirySourcePrimary" attribute.
    */
   public void setInquirySourcePrimary(InquirySourcePrimary inquirySourcePrimary) {
      this.inquirySourcePrimary = inquirySourcePrimary;
   }

   /**
    * Sets the value of the "inquirySourceSecondary" attribute.
    *
    * @param inquirySourceSecondary"
    *     The value of the "inquirySourceSecondary" attribute.
    */
   public void setInquirySourceSecondary(InquirySourceSecondary inquirySourceSecondary) {
      this.inquirySourceSecondary = inquirySourceSecondary;
   }

   /**
    * Sets the value of the "inquiryStatus" attribute.
    *
    * @param inquiryStatus"
    *     The value of the "inquiryStatus" attribute.
    */
   public void setInquiryStatus(InquiryStatus inquiryStatus) {
      this.inquiryStatus = inquiryStatus;
   }

   /**
    * Sets the value of the "leadPaint" attribute.
    *
    * @param leadPaint"
    *     The value of the "leadPaint" attribute.
    */
   public void setLeadPaint(List<LeadPaint> leadPaint) {
      this.leadPaint = leadPaint;
   }

   /**
    * Sets the value of the "productInterest" attribute.
    *
    * @param productInterest"
    *     The value of the "productInterest" attribute.
    */
   public void setProductInterest(List<ProductInterest> productInterest) {
      this.productInterest = productInterest;
   }

   /**
    * Sets the value of the "promoter" attribute.
    *
    * @param promoter"
    *     The value of the "promoter" attribute.
    */
   public void setPromoter(Employee promoter) {
      this.promoter = promoter;
   }

   /**
    * Sets the value of the "setBy" attribute.
    *
    * @param setBy"
    *     The value of the "setBy" attribute.
    */
   public void setSetBy(Employee setBy) {
      this.setBy = setBy;
   }

   /**
    * Sets the value of the "telemarketer" attribute.
    *
    * @param telemarketer"
    *     The value of the "telemarketer" attribute.
    */
   public void setTelemarketer(Employee telemarketer) {
      this.telemarketer = telemarketer;
   }

}