/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.List;
import msharpmodel.Company;
import msharpmodel.Inquiry;
import msharpmodel.InquirySourcePrimary;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class InquirySourceSecondary {

    private String companyId;
    private String id;
    private String inquirySourcePrimaryId;
    private boolean isActive;
    private String name;
    private Company company;
    private List<Inquiry> inquiry;
    private InquirySourcePrimary inquirySourcePrimary;

    /**
     * Constructor without parameter.
     * 
     */
    public InquirySourceSecondary() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public InquirySourceSecondary(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "inquirySourcePrimaryId" attribute.
    *
    * @return The value of the "inquirySourcePrimaryId" attribute.
    */
   public String getInquirySourcePrimaryId() {
      return inquirySourcePrimaryId;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "company" attribute.
    *
    * @return The value of the "company" attribute.
    */
   public Company getCompany() {
      return company;
   }
   
   /**
    * Returns the value of the "inquiry" attribute.
    *
    * @return The value of the "inquiry" attribute.
    */
   public List<Inquiry> getInquiry() {
      return inquiry;
   }
   
   /**
    * Returns the value of the "inquirySourcePrimary" attribute.
    *
    * @return The value of the "inquirySourcePrimary" attribute.
    */
   public InquirySourcePrimary getInquirySourcePrimary() {
      return inquirySourcePrimary;
   }
   
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "inquirySourcePrimaryId" attribute.
    *
    * @param inquirySourcePrimaryId
    *     The value of the "inquirySourcePrimaryId" attribute.
    */
   public void setInquirySourcePrimaryId(String inquirySourcePrimaryId) {
      this.inquirySourcePrimaryId = inquirySourcePrimaryId;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "company" attribute.
    *
    * @param company"
    *     The value of the "company" attribute.
    */
   public void setCompany(Company company) {
      this.company = company;
   }

   /**
    * Sets the value of the "inquiry" attribute.
    *
    * @param inquiry"
    *     The value of the "inquiry" attribute.
    */
   public void setInquiry(List<Inquiry> inquiry) {
      this.inquiry = inquiry;
   }

   /**
    * Sets the value of the "inquirySourcePrimary" attribute.
    *
    * @param inquirySourcePrimary"
    *     The value of the "inquirySourcePrimary" attribute.
    */
   public void setInquirySourcePrimary(InquirySourcePrimary inquirySourcePrimary) {
      this.inquirySourcePrimary = inquirySourcePrimary;
   }

}