/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.JobProduct;
import msharpmodel.JobProductCostType;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class JobProductCost {

    private double amount;
    private String createdBy;
    private Date createdDate;
    private Date date;
    private String description;
    private String id;
    private boolean isActive;
    private String jobProductCostId;
    private String jobProductId;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String paidTo;
    private JobProduct jobProduct;
    private JobProductCostType jobProductCostType;

    /**
     * Constructor without parameter.
     * 
     */
    public JobProductCost() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public JobProductCost(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "amount" attribute.
    *
    * @return The value of the "amount" attribute.
    */
   public double getAmount() {
      return amount;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "date" attribute.
    *
    * @return The value of the "date" attribute.
    */
   public Date getDate() {
      return date;
   }
   /**
    * Returns the value of the "description" attribute.
    *
    * @return The value of the "description" attribute.
    */
   public String getDescription() {
      return description;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "jobProductCostId" attribute.
    *
    * @return The value of the "jobProductCostId" attribute.
    */
   public String getJobProductCostId() {
      return jobProductCostId;
   }
   /**
    * Returns the value of the "jobProductId" attribute.
    *
    * @return The value of the "jobProductId" attribute.
    */
   public String getJobProductId() {
      return jobProductId;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "paidTo" attribute.
    *
    * @return The value of the "paidTo" attribute.
    */
   public String getPaidTo() {
      return paidTo;
   }
   /**
    * Returns the value of the "jobProduct" attribute.
    *
    * @return The value of the "jobProduct" attribute.
    */
   public JobProduct getJobProduct() {
      return jobProduct;
   }
   
   /**
    * Returns the value of the "jobProductCostType" attribute.
    *
    * @return The value of the "jobProductCostType" attribute.
    */
   public JobProductCostType getJobProductCostType() {
      return jobProductCostType;
   }
   
   /**
    * Sets the value of the "amount" attribute.
    *
    * @param amount
    *     The value of the "amount" attribute.
    */
   public void setAmount(double amount) {
      this.amount = amount;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "date" attribute.
    *
    * @param date
    *     The value of the "date" attribute.
    */
   public void setDate(Date date) {
      this.date = date;
   }
   /**
    * Sets the value of the "description" attribute.
    *
    * @param description
    *     The value of the "description" attribute.
    */
   public void setDescription(String description) {
      this.description = description;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "jobProductCostId" attribute.
    *
    * @param jobProductCostId
    *     The value of the "jobProductCostId" attribute.
    */
   public void setJobProductCostId(String jobProductCostId) {
      this.jobProductCostId = jobProductCostId;
   }
   /**
    * Sets the value of the "jobProductId" attribute.
    *
    * @param jobProductId
    *     The value of the "jobProductId" attribute.
    */
   public void setJobProductId(String jobProductId) {
      this.jobProductId = jobProductId;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "paidTo" attribute.
    *
    * @param paidTo
    *     The value of the "paidTo" attribute.
    */
   public void setPaidTo(String paidTo) {
      this.paidTo = paidTo;
   }
   /**
    * Sets the value of the "jobProduct" attribute.
    *
    * @param jobProduct"
    *     The value of the "jobProduct" attribute.
    */
   public void setJobProduct(JobProduct jobProduct) {
      this.jobProduct = jobProduct;
   }

   /**
    * Sets the value of the "jobProductCostType" attribute.
    *
    * @param jobProductCostType"
    *     The value of the "jobProductCostType" attribute.
    */
   public void setJobProductCostType(JobProductCostType jobProductCostType) {
      this.jobProductCostType = jobProductCostType;
   }

}