/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import java.util.List;
import msharpmodel.Employee;
import msharpmodel.JobProduct;
import msharpmodel.JobProductCommissionPayments;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class JobProductCommission {

    private double adjustmentAmount;
    private String adjustmentDescription;
    private double commissionAmount;
    private String companyId;
    private String createdBy;
    private Date createdDate;
    private String id;
    private boolean isActive;
    private String jobProductId;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String salespersonId;
    private JobProduct jobProduct;
    private List<JobProductCommissionPayments> jobProductCommissionPayment;
    private Employee salesperson;

    /**
     * Constructor without parameter.
     * 
     */
    public JobProductCommission() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public JobProductCommission(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "adjustmentAmount" attribute.
    *
    * @return The value of the "adjustmentAmount" attribute.
    */
   public double getAdjustmentAmount() {
      return adjustmentAmount;
   }
   /**
    * Returns the value of the "adjustmentDescription" attribute.
    *
    * @return The value of the "adjustmentDescription" attribute.
    */
   public String getAdjustmentDescription() {
      return adjustmentDescription;
   }
   /**
    * Returns the value of the "commissionAmount" attribute.
    *
    * @return The value of the "commissionAmount" attribute.
    */
   public double getCommissionAmount() {
      return commissionAmount;
   }
   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "jobProductId" attribute.
    *
    * @return The value of the "jobProductId" attribute.
    */
   public String getJobProductId() {
      return jobProductId;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "salespersonId" attribute.
    *
    * @return The value of the "salespersonId" attribute.
    */
   public String getSalespersonId() {
      return salespersonId;
   }
   /**
    * Returns the value of the "jobProduct" attribute.
    *
    * @return The value of the "jobProduct" attribute.
    */
   public JobProduct getJobProduct() {
      return jobProduct;
   }
   
   /**
    * Returns the value of the "jobProductCommissionPayment" attribute.
    *
    * @return The value of the "jobProductCommissionPayment" attribute.
    */
   public List<JobProductCommissionPayments> getJobProductCommissionPayment() {
      return jobProductCommissionPayment;
   }
   
   /**
    * Returns the value of the "salesperson" attribute.
    *
    * @return The value of the "salesperson" attribute.
    */
   public Employee getSalesperson() {
      return salesperson;
   }
   
   /**
    * Sets the value of the "adjustmentAmount" attribute.
    *
    * @param adjustmentAmount
    *     The value of the "adjustmentAmount" attribute.
    */
   public void setAdjustmentAmount(double adjustmentAmount) {
      this.adjustmentAmount = adjustmentAmount;
   }
   /**
    * Sets the value of the "adjustmentDescription" attribute.
    *
    * @param adjustmentDescription
    *     The value of the "adjustmentDescription" attribute.
    */
   public void setAdjustmentDescription(String adjustmentDescription) {
      this.adjustmentDescription = adjustmentDescription;
   }
   /**
    * Sets the value of the "commissionAmount" attribute.
    *
    * @param commissionAmount
    *     The value of the "commissionAmount" attribute.
    */
   public void setCommissionAmount(double commissionAmount) {
      this.commissionAmount = commissionAmount;
   }
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "jobProductId" attribute.
    *
    * @param jobProductId
    *     The value of the "jobProductId" attribute.
    */
   public void setJobProductId(String jobProductId) {
      this.jobProductId = jobProductId;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "salespersonId" attribute.
    *
    * @param salespersonId
    *     The value of the "salespersonId" attribute.
    */
   public void setSalespersonId(String salespersonId) {
      this.salespersonId = salespersonId;
   }
   /**
    * Sets the value of the "jobProduct" attribute.
    *
    * @param jobProduct"
    *     The value of the "jobProduct" attribute.
    */
   public void setJobProduct(JobProduct jobProduct) {
      this.jobProduct = jobProduct;
   }

   /**
    * Sets the value of the "jobProductCommissionPayment" attribute.
    *
    * @param jobProductCommissionPayment"
    *     The value of the "jobProductCommissionPayment" attribute.
    */
   public void setJobProductCommissionPayment(List<JobProductCommissionPayments> jobProductCommissionPayment) {
      this.jobProductCommissionPayment = jobProductCommissionPayment;
   }

   /**
    * Sets the value of the "salesperson" attribute.
    *
    * @param salesperson"
    *     The value of the "salesperson" attribute.
    */
   public void setSalesperson(Employee salesperson) {
      this.salesperson = salesperson;
   }

}