/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import java.util.List;
import msharpmodel.Employee;
import msharpmodel.Job;
import msharpmodel.JobProductCommission;
import msharpmodel.JobProductCost;
import msharpmodel.JobProductDetail;
import msharpmodel.ProcessStep;
import msharpmodel.ProductType;
import msharpmodel.ServiceOrder;
import msharpmodel.WorkCrew;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class JobProduct {

    private double adjustedPrice;
    private double adjustment;
    private Date completedDate;
    private String id;
    private boolean isActive;
    private String jobId;
    private String note;
    private double price;
    private String productionNote;
    private String productTypeId;
    private String projectManagerId;
    private Date saleDate;
    private String salesperson1id;
    private String salesperson2id;
    private String saleType;
    private Date serviceEndDate;
    private Date serviceStartDate;
    private String status;
    private Date warrantyEndDate;
    private Date warrantyStartDate;
    private String workCrewId;
    private List<JobProductCommission> commission;
    private Job job;
    private List<JobProductCost> jobProductCost;
    private List<JobProductDetail> jobProductDetail;
    private ProductType jobProductType;
    private List<ProcessStep> processStep;
    private Employee projectManager;
    private Employee salesperson1;
    private Employee salesperson2;
    private List<ServiceOrder> serviceOrder;
    private WorkCrew workCrew;
    private List<Employee> worker;

    /**
     * Constructor without parameter.
     * 
     */
    public JobProduct() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public JobProduct(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "adjustedPrice" attribute.
    *
    * @return The value of the "adjustedPrice" attribute.
    */
   public double getAdjustedPrice() {
      return adjustedPrice;
   }
   /**
    * Returns the value of the "adjustment" attribute.
    *
    * @return The value of the "adjustment" attribute.
    */
   public double getAdjustment() {
      return adjustment;
   }
   /**
    * Returns the value of the "completedDate" attribute.
    *
    * @return The value of the "completedDate" attribute.
    */
   public Date getCompletedDate() {
      return completedDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "jobId" attribute.
    *
    * @return The value of the "jobId" attribute.
    */
   public String getJobId() {
      return jobId;
   }
   /**
    * Returns the value of the "note" attribute.
    *
    * @return The value of the "note" attribute.
    */
   public String getNote() {
      return note;
   }
   /**
    * Returns the value of the "price" attribute.
    *
    * @return The value of the "price" attribute.
    */
   public double getPrice() {
      return price;
   }
   /**
    * Returns the value of the "productionNote" attribute.
    *
    * @return The value of the "productionNote" attribute.
    */
   public String getProductionNote() {
      return productionNote;
   }
   /**
    * Returns the value of the "productTypeId" attribute.
    *
    * @return The value of the "productTypeId" attribute.
    */
   public String getProductTypeId() {
      return productTypeId;
   }
   /**
    * Returns the value of the "projectManagerId" attribute.
    *
    * @return The value of the "projectManagerId" attribute.
    */
   public String getProjectManagerId() {
      return projectManagerId;
   }
   /**
    * Returns the value of the "saleDate" attribute.
    *
    * @return The value of the "saleDate" attribute.
    */
   public Date getSaleDate() {
      return saleDate;
   }
   /**
    * Returns the value of the "salesperson1id" attribute.
    *
    * @return The value of the "salesperson1id" attribute.
    */
   public String getSalesperson1id() {
      return salesperson1id;
   }
   /**
    * Returns the value of the "salesperson2id" attribute.
    *
    * @return The value of the "salesperson2id" attribute.
    */
   public String getSalesperson2id() {
      return salesperson2id;
   }
   /**
    * Returns the value of the "saleType" attribute.
    *
    * @return The value of the "saleType" attribute.
    */
   public String getSaleType() {
      return saleType;
   }
   /**
    * Returns the value of the "serviceEndDate" attribute.
    *
    * @return The value of the "serviceEndDate" attribute.
    */
   public Date getServiceEndDate() {
      return serviceEndDate;
   }
   /**
    * Returns the value of the "serviceStartDate" attribute.
    *
    * @return The value of the "serviceStartDate" attribute.
    */
   public Date getServiceStartDate() {
      return serviceStartDate;
   }
   /**
    * Returns the value of the "status" attribute.
    *
    * @return The value of the "status" attribute.
    */
   public String getStatus() {
      return status;
   }
   /**
    * Returns the value of the "warrantyEndDate" attribute.
    *
    * @return The value of the "warrantyEndDate" attribute.
    */
   public Date getWarrantyEndDate() {
      return warrantyEndDate;
   }
   /**
    * Returns the value of the "warrantyStartDate" attribute.
    *
    * @return The value of the "warrantyStartDate" attribute.
    */
   public Date getWarrantyStartDate() {
      return warrantyStartDate;
   }
   /**
    * Returns the value of the "workCrewId" attribute.
    *
    * @return The value of the "workCrewId" attribute.
    */
   public String getWorkCrewId() {
      return workCrewId;
   }
   /**
    * Returns the value of the "commission" attribute.
    *
    * @return The value of the "commission" attribute.
    */
   public List<JobProductCommission> getCommission() {
      return commission;
   }
   
   /**
    * Returns the value of the "job" attribute.
    *
    * @return The value of the "job" attribute.
    */
   public Job getJob() {
      return job;
   }
   
   /**
    * Returns the value of the "jobProductCost" attribute.
    *
    * @return The value of the "jobProductCost" attribute.
    */
   public List<JobProductCost> getJobProductCost() {
      return jobProductCost;
   }
   
   /**
    * Returns the value of the "jobProductDetail" attribute.
    *
    * @return The value of the "jobProductDetail" attribute.
    */
   public List<JobProductDetail> getJobProductDetail() {
      return jobProductDetail;
   }
   
   /**
    * Returns the value of the "jobProductType" attribute.
    *
    * @return The value of the "jobProductType" attribute.
    */
   public ProductType getJobProductType() {
      return jobProductType;
   }
   
   /**
    * Returns the value of the "processStep" attribute.
    *
    * @return The value of the "processStep" attribute.
    */
   public List<ProcessStep> getProcessStep() {
      return processStep;
   }
   
   /**
    * Returns the value of the "projectManager" attribute.
    *
    * @return The value of the "projectManager" attribute.
    */
   public Employee getProjectManager() {
      return projectManager;
   }
   
   /**
    * Returns the value of the "salesperson1" attribute.
    *
    * @return The value of the "salesperson1" attribute.
    */
   public Employee getSalesperson1() {
      return salesperson1;
   }
   
   /**
    * Returns the value of the "salesperson2" attribute.
    *
    * @return The value of the "salesperson2" attribute.
    */
   public Employee getSalesperson2() {
      return salesperson2;
   }
   
   /**
    * Returns the value of the "serviceOrder" attribute.
    *
    * @return The value of the "serviceOrder" attribute.
    */
   public List<ServiceOrder> getServiceOrder() {
      return serviceOrder;
   }
   
   /**
    * Returns the value of the "workCrew" attribute.
    *
    * @return The value of the "workCrew" attribute.
    */
   public WorkCrew getWorkCrew() {
      return workCrew;
   }
   
   /**
    * Returns the value of the "worker" attribute.
    *
    * @return The value of the "worker" attribute.
    */
   public List<Employee> getWorker() {
      return worker;
   }
   
   /**
    * Sets the value of the "adjustedPrice" attribute.
    *
    * @param adjustedPrice
    *     The value of the "adjustedPrice" attribute.
    */
   public void setAdjustedPrice(double adjustedPrice) {
      this.adjustedPrice = adjustedPrice;
   }
   /**
    * Sets the value of the "adjustment" attribute.
    *
    * @param adjustment
    *     The value of the "adjustment" attribute.
    */
   public void setAdjustment(double adjustment) {
      this.adjustment = adjustment;
   }
   /**
    * Sets the value of the "completedDate" attribute.
    *
    * @param completedDate
    *     The value of the "completedDate" attribute.
    */
   public void setCompletedDate(Date completedDate) {
      this.completedDate = completedDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "jobId" attribute.
    *
    * @param jobId
    *     The value of the "jobId" attribute.
    */
   public void setJobId(String jobId) {
      this.jobId = jobId;
   }
   /**
    * Sets the value of the "note" attribute.
    *
    * @param note
    *     The value of the "note" attribute.
    */
   public void setNote(String note) {
      this.note = note;
   }
   /**
    * Sets the value of the "price" attribute.
    *
    * @param price
    *     The value of the "price" attribute.
    */
   public void setPrice(double price) {
      this.price = price;
   }
   /**
    * Sets the value of the "productionNote" attribute.
    *
    * @param productionNote
    *     The value of the "productionNote" attribute.
    */
   public void setProductionNote(String productionNote) {
      this.productionNote = productionNote;
   }
   /**
    * Sets the value of the "productTypeId" attribute.
    *
    * @param productTypeId
    *     The value of the "productTypeId" attribute.
    */
   public void setProductTypeId(String productTypeId) {
      this.productTypeId = productTypeId;
   }
   /**
    * Sets the value of the "projectManagerId" attribute.
    *
    * @param projectManagerId
    *     The value of the "projectManagerId" attribute.
    */
   public void setProjectManagerId(String projectManagerId) {
      this.projectManagerId = projectManagerId;
   }
   /**
    * Sets the value of the "saleDate" attribute.
    *
    * @param saleDate
    *     The value of the "saleDate" attribute.
    */
   public void setSaleDate(Date saleDate) {
      this.saleDate = saleDate;
   }
   /**
    * Sets the value of the "salesperson1id" attribute.
    *
    * @param salesperson1id
    *     The value of the "salesperson1id" attribute.
    */
   public void setSalesperson1id(String salesperson1id) {
      this.salesperson1id = salesperson1id;
   }
   /**
    * Sets the value of the "salesperson2id" attribute.
    *
    * @param salesperson2id
    *     The value of the "salesperson2id" attribute.
    */
   public void setSalesperson2id(String salesperson2id) {
      this.salesperson2id = salesperson2id;
   }
   /**
    * Sets the value of the "saleType" attribute.
    *
    * @param saleType
    *     The value of the "saleType" attribute.
    */
   public void setSaleType(String saleType) {
      this.saleType = saleType;
   }
   /**
    * Sets the value of the "serviceEndDate" attribute.
    *
    * @param serviceEndDate
    *     The value of the "serviceEndDate" attribute.
    */
   public void setServiceEndDate(Date serviceEndDate) {
      this.serviceEndDate = serviceEndDate;
   }
   /**
    * Sets the value of the "serviceStartDate" attribute.
    *
    * @param serviceStartDate
    *     The value of the "serviceStartDate" attribute.
    */
   public void setServiceStartDate(Date serviceStartDate) {
      this.serviceStartDate = serviceStartDate;
   }
   /**
    * Sets the value of the "status" attribute.
    *
    * @param status
    *     The value of the "status" attribute.
    */
   public void setStatus(String status) {
      this.status = status;
   }
   /**
    * Sets the value of the "warrantyEndDate" attribute.
    *
    * @param warrantyEndDate
    *     The value of the "warrantyEndDate" attribute.
    */
   public void setWarrantyEndDate(Date warrantyEndDate) {
      this.warrantyEndDate = warrantyEndDate;
   }
   /**
    * Sets the value of the "warrantyStartDate" attribute.
    *
    * @param warrantyStartDate
    *     The value of the "warrantyStartDate" attribute.
    */
   public void setWarrantyStartDate(Date warrantyStartDate) {
      this.warrantyStartDate = warrantyStartDate;
   }
   /**
    * Sets the value of the "workCrewId" attribute.
    *
    * @param workCrewId
    *     The value of the "workCrewId" attribute.
    */
   public void setWorkCrewId(String workCrewId) {
      this.workCrewId = workCrewId;
   }
   /**
    * Sets the value of the "commission" attribute.
    *
    * @param commission"
    *     The value of the "commission" attribute.
    */
   public void setCommission(List<JobProductCommission> commission) {
      this.commission = commission;
   }

   /**
    * Sets the value of the "job" attribute.
    *
    * @param job"
    *     The value of the "job" attribute.
    */
   public void setJob(Job job) {
      this.job = job;
   }

   /**
    * Sets the value of the "jobProductCost" attribute.
    *
    * @param jobProductCost"
    *     The value of the "jobProductCost" attribute.
    */
   public void setJobProductCost(List<JobProductCost> jobProductCost) {
      this.jobProductCost = jobProductCost;
   }

   /**
    * Sets the value of the "jobProductDetail" attribute.
    *
    * @param jobProductDetail"
    *     The value of the "jobProductDetail" attribute.
    */
   public void setJobProductDetail(List<JobProductDetail> jobProductDetail) {
      this.jobProductDetail = jobProductDetail;
   }

   /**
    * Sets the value of the "jobProductType" attribute.
    *
    * @param jobProductType"
    *     The value of the "jobProductType" attribute.
    */
   public void setJobProductType(ProductType jobProductType) {
      this.jobProductType = jobProductType;
   }

   /**
    * Sets the value of the "processStep" attribute.
    *
    * @param processStep"
    *     The value of the "processStep" attribute.
    */
   public void setProcessStep(List<ProcessStep> processStep) {
      this.processStep = processStep;
   }

   /**
    * Sets the value of the "projectManager" attribute.
    *
    * @param projectManager"
    *     The value of the "projectManager" attribute.
    */
   public void setProjectManager(Employee projectManager) {
      this.projectManager = projectManager;
   }

   /**
    * Sets the value of the "salesperson1" attribute.
    *
    * @param salesperson1"
    *     The value of the "salesperson1" attribute.
    */
   public void setSalesperson1(Employee salesperson1) {
      this.salesperson1 = salesperson1;
   }

   /**
    * Sets the value of the "salesperson2" attribute.
    *
    * @param salesperson2"
    *     The value of the "salesperson2" attribute.
    */
   public void setSalesperson2(Employee salesperson2) {
      this.salesperson2 = salesperson2;
   }

   /**
    * Sets the value of the "serviceOrder" attribute.
    *
    * @param serviceOrder"
    *     The value of the "serviceOrder" attribute.
    */
   public void setServiceOrder(List<ServiceOrder> serviceOrder) {
      this.serviceOrder = serviceOrder;
   }

   /**
    * Sets the value of the "workCrew" attribute.
    *
    * @param workCrew"
    *     The value of the "workCrew" attribute.
    */
   public void setWorkCrew(WorkCrew workCrew) {
      this.workCrew = workCrew;
   }

   /**
    * Sets the value of the "worker" attribute.
    *
    * @param worker"
    *     The value of the "worker" attribute.
    */
   public void setWorker(List<Employee> worker) {
      this.worker = worker;
   }

}