/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import msharpmodel.JobProduct;
import msharpmodel.ProductDetail;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class JobProductDetail {

    private String definable1;
    private String definable2;
    private String definable3;
    private String id;
    private boolean isActive;
    private String jobProductId;
    private String note;
    private double price;
    private String productDetailId;
    private String quantity;
    private String unit;
    private JobProduct jobProduct;
    private ProductDetail productDetail;

    /**
     * Constructor without parameter.
     * 
     */
    public JobProductDetail() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public JobProductDetail(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "definable1" attribute.
    *
    * @return The value of the "definable1" attribute.
    */
   public String getDefinable1() {
      return definable1;
   }
   /**
    * Returns the value of the "definable2" attribute.
    *
    * @return The value of the "definable2" attribute.
    */
   public String getDefinable2() {
      return definable2;
   }
   /**
    * Returns the value of the "definable3" attribute.
    *
    * @return The value of the "definable3" attribute.
    */
   public String getDefinable3() {
      return definable3;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "jobProductId" attribute.
    *
    * @return The value of the "jobProductId" attribute.
    */
   public String getJobProductId() {
      return jobProductId;
   }
   /**
    * Returns the value of the "note" attribute.
    *
    * @return The value of the "note" attribute.
    */
   public String getNote() {
      return note;
   }
   /**
    * Returns the value of the "price" attribute.
    *
    * @return The value of the "price" attribute.
    */
   public double getPrice() {
      return price;
   }
   /**
    * Returns the value of the "productDetailId" attribute.
    *
    * @return The value of the "productDetailId" attribute.
    */
   public String getProductDetailId() {
      return productDetailId;
   }
   /**
    * Returns the value of the "quantity" attribute.
    *
    * @return The value of the "quantity" attribute.
    */
   public String getQuantity() {
      return quantity;
   }
   /**
    * Returns the value of the "unit" attribute.
    *
    * @return The value of the "unit" attribute.
    */
   public String getUnit() {
      return unit;
   }
   /**
    * Returns the value of the "jobProduct" attribute.
    *
    * @return The value of the "jobProduct" attribute.
    */
   public JobProduct getJobProduct() {
      return jobProduct;
   }
   
   /**
    * Returns the value of the "productDetail" attribute.
    *
    * @return The value of the "productDetail" attribute.
    */
   public ProductDetail getProductDetail() {
      return productDetail;
   }
   
   /**
    * Sets the value of the "definable1" attribute.
    *
    * @param definable1
    *     The value of the "definable1" attribute.
    */
   public void setDefinable1(String definable1) {
      this.definable1 = definable1;
   }
   /**
    * Sets the value of the "definable2" attribute.
    *
    * @param definable2
    *     The value of the "definable2" attribute.
    */
   public void setDefinable2(String definable2) {
      this.definable2 = definable2;
   }
   /**
    * Sets the value of the "definable3" attribute.
    *
    * @param definable3
    *     The value of the "definable3" attribute.
    */
   public void setDefinable3(String definable3) {
      this.definable3 = definable3;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "jobProductId" attribute.
    *
    * @param jobProductId
    *     The value of the "jobProductId" attribute.
    */
   public void setJobProductId(String jobProductId) {
      this.jobProductId = jobProductId;
   }
   /**
    * Sets the value of the "note" attribute.
    *
    * @param note
    *     The value of the "note" attribute.
    */
   public void setNote(String note) {
      this.note = note;
   }
   /**
    * Sets the value of the "price" attribute.
    *
    * @param price
    *     The value of the "price" attribute.
    */
   public void setPrice(double price) {
      this.price = price;
   }
   /**
    * Sets the value of the "productDetailId" attribute.
    *
    * @param productDetailId
    *     The value of the "productDetailId" attribute.
    */
   public void setProductDetailId(String productDetailId) {
      this.productDetailId = productDetailId;
   }
   /**
    * Sets the value of the "quantity" attribute.
    *
    * @param quantity
    *     The value of the "quantity" attribute.
    */
   public void setQuantity(String quantity) {
      this.quantity = quantity;
   }
   /**
    * Sets the value of the "unit" attribute.
    *
    * @param unit
    *     The value of the "unit" attribute.
    */
   public void setUnit(String unit) {
      this.unit = unit;
   }
   /**
    * Sets the value of the "jobProduct" attribute.
    *
    * @param jobProduct"
    *     The value of the "jobProduct" attribute.
    */
   public void setJobProduct(JobProduct jobProduct) {
      this.jobProduct = jobProduct;
   }

   /**
    * Sets the value of the "productDetail" attribute.
    *
    * @param productDetail"
    *     The value of the "productDetail" attribute.
    */
   public void setProductDetail(ProductDetail productDetail) {
      this.productDetail = productDetail;
   }

}