/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.List;
import msharpmodel.LeadPaintFirm;
import msharpmodel.LeadPaintToWorker;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class LeadPaintWorker {

    private String address;
    private String city;
    private String email;
    private String firmId;
    private String firstName;
    private String id;
    private boolean isActive;
    private String lastName;
    private String phone;
    private String state;
    private String zip;
    private List<LeadPaintToWorker> leadPaint;
    private LeadPaintFirm leadPaintFirm;

    /**
     * Constructor without parameter.
     * 
     */
    public LeadPaintWorker() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public LeadPaintWorker(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "address" attribute.
    *
    * @return The value of the "address" attribute.
    */
   public String getAddress() {
      return address;
   }
   /**
    * Returns the value of the "city" attribute.
    *
    * @return The value of the "city" attribute.
    */
   public String getCity() {
      return city;
   }
   /**
    * Returns the value of the "email" attribute.
    *
    * @return The value of the "email" attribute.
    */
   public String getEmail() {
      return email;
   }
   /**
    * Returns the value of the "firmId" attribute.
    *
    * @return The value of the "firmId" attribute.
    */
   public String getFirmId() {
      return firmId;
   }
   /**
    * Returns the value of the "firstName" attribute.
    *
    * @return The value of the "firstName" attribute.
    */
   public String getFirstName() {
      return firstName;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "lastName" attribute.
    *
    * @return The value of the "lastName" attribute.
    */
   public String getLastName() {
      return lastName;
   }
   /**
    * Returns the value of the "phone" attribute.
    *
    * @return The value of the "phone" attribute.
    */
   public String getPhone() {
      return phone;
   }
   /**
    * Returns the value of the "state" attribute.
    *
    * @return The value of the "state" attribute.
    */
   public String getState() {
      return state;
   }
   /**
    * Returns the value of the "zip" attribute.
    *
    * @return The value of the "zip" attribute.
    */
   public String getZip() {
      return zip;
   }
   /**
    * Returns the value of the "leadPaint" attribute.
    *
    * @return The value of the "leadPaint" attribute.
    */
   public List<LeadPaintToWorker> getLeadPaint() {
      return leadPaint;
   }
   
   /**
    * Returns the value of the "leadPaintFirm" attribute.
    *
    * @return The value of the "leadPaintFirm" attribute.
    */
   public LeadPaintFirm getLeadPaintFirm() {
      return leadPaintFirm;
   }
   
   /**
    * Sets the value of the "address" attribute.
    *
    * @param address
    *     The value of the "address" attribute.
    */
   public void setAddress(String address) {
      this.address = address;
   }
   /**
    * Sets the value of the "city" attribute.
    *
    * @param city
    *     The value of the "city" attribute.
    */
   public void setCity(String city) {
      this.city = city;
   }
   /**
    * Sets the value of the "email" attribute.
    *
    * @param email
    *     The value of the "email" attribute.
    */
   public void setEmail(String email) {
      this.email = email;
   }
   /**
    * Sets the value of the "firmId" attribute.
    *
    * @param firmId
    *     The value of the "firmId" attribute.
    */
   public void setFirmId(String firmId) {
      this.firmId = firmId;
   }
   /**
    * Sets the value of the "firstName" attribute.
    *
    * @param firstName
    *     The value of the "firstName" attribute.
    */
   public void setFirstName(String firstName) {
      this.firstName = firstName;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "lastName" attribute.
    *
    * @param lastName
    *     The value of the "lastName" attribute.
    */
   public void setLastName(String lastName) {
      this.lastName = lastName;
   }
   /**
    * Sets the value of the "phone" attribute.
    *
    * @param phone
    *     The value of the "phone" attribute.
    */
   public void setPhone(String phone) {
      this.phone = phone;
   }
   /**
    * Sets the value of the "state" attribute.
    *
    * @param state
    *     The value of the "state" attribute.
    */
   public void setState(String state) {
      this.state = state;
   }
   /**
    * Sets the value of the "zip" attribute.
    *
    * @param zip
    *     The value of the "zip" attribute.
    */
   public void setZip(String zip) {
      this.zip = zip;
   }
   /**
    * Sets the value of the "leadPaint" attribute.
    *
    * @param leadPaint"
    *     The value of the "leadPaint" attribute.
    */
   public void setLeadPaint(List<LeadPaintToWorker> leadPaint) {
      this.leadPaint = leadPaint;
   }

   /**
    * Sets the value of the "leadPaintFirm" attribute.
    *
    * @param leadPaintFirm"
    *     The value of the "leadPaintFirm" attribute.
    */
   public void setLeadPaintFirm(LeadPaintFirm leadPaintFirm) {
      this.leadPaintFirm = leadPaintFirm;
   }

}