/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Company;
import msharpmodel.LeadPaint;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class LeadPaintAttachment {

    private String attachmentFileName;
    private String attachmentPath;
    private String companyId;
    private Date date;
    private String description;
    private String id;
    private boolean isActive;
    private String leadPaintId;
    private int type;
    private Company company;
    private LeadPaint leadPaint;

    /**
     * Constructor without parameter.
     * 
     */
    public LeadPaintAttachment() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public LeadPaintAttachment(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "attachmentFileName" attribute.
    *
    * @return The value of the "attachmentFileName" attribute.
    */
   public String getAttachmentFileName() {
      return attachmentFileName;
   }
   /**
    * Returns the value of the "attachmentPath" attribute.
    *
    * @return The value of the "attachmentPath" attribute.
    */
   public String getAttachmentPath() {
      return attachmentPath;
   }
   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "date" attribute.
    *
    * @return The value of the "date" attribute.
    */
   public Date getDate() {
      return date;
   }
   /**
    * Returns the value of the "description" attribute.
    *
    * @return The value of the "description" attribute.
    */
   public String getDescription() {
      return description;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "leadPaintId" attribute.
    *
    * @return The value of the "leadPaintId" attribute.
    */
   public String getLeadPaintId() {
      return leadPaintId;
   }
   /**
    * Returns the value of the "type" attribute.
    *
    * @return The value of the "type" attribute.
    */
   public int getType() {
      return type;
   }
   /**
    * Returns the value of the "company" attribute.
    *
    * @return The value of the "company" attribute.
    */
   public Company getCompany() {
      return company;
   }
   
   /**
    * Returns the value of the "leadPaint" attribute.
    *
    * @return The value of the "leadPaint" attribute.
    */
   public LeadPaint getLeadPaint() {
      return leadPaint;
   }
   
   /**
    * Sets the value of the "attachmentFileName" attribute.
    *
    * @param attachmentFileName
    *     The value of the "attachmentFileName" attribute.
    */
   public void setAttachmentFileName(String attachmentFileName) {
      this.attachmentFileName = attachmentFileName;
   }
   /**
    * Sets the value of the "attachmentPath" attribute.
    *
    * @param attachmentPath
    *     The value of the "attachmentPath" attribute.
    */
   public void setAttachmentPath(String attachmentPath) {
      this.attachmentPath = attachmentPath;
   }
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "date" attribute.
    *
    * @param date
    *     The value of the "date" attribute.
    */
   public void setDate(Date date) {
      this.date = date;
   }
   /**
    * Sets the value of the "description" attribute.
    *
    * @param description
    *     The value of the "description" attribute.
    */
   public void setDescription(String description) {
      this.description = description;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "leadPaintId" attribute.
    *
    * @param leadPaintId
    *     The value of the "leadPaintId" attribute.
    */
   public void setLeadPaintId(String leadPaintId) {
      this.leadPaintId = leadPaintId;
   }
   /**
    * Sets the value of the "type" attribute.
    *
    * @param type
    *     The value of the "type" attribute.
    */
   public void setType(int type) {
      this.type = type;
   }
   /**
    * Sets the value of the "company" attribute.
    *
    * @param company"
    *     The value of the "company" attribute.
    */
   public void setCompany(Company company) {
      this.company = company;
   }

   /**
    * Sets the value of the "leadPaint" attribute.
    *
    * @param leadPaint"
    *     The value of the "leadPaint" attribute.
    */
   public void setLeadPaint(LeadPaint leadPaint) {
      this.leadPaint = leadPaint;
   }

}