/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Contract;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Loan {

    private String contractId;
    private String createdBy;
    private Date createdDate;
    private String financedBy;
    private String id;
    private boolean isActive;
    private Date lastUpdate;
    private String lastUpdateBy;
    private Date loanApprovedDate;
    private String loanCreditScore;
    private String loanNumber;
    private String loanRate;
    private String loanStatus;
    private String loanTerm;
    private String loanType;
    private String notes;
    private Contract contract;

    /**
     * Constructor without parameter.
     * 
     */
    public Loan() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Loan(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "contractId" attribute.
    *
    * @return The value of the "contractId" attribute.
    */
   public String getContractId() {
      return contractId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "financedBy" attribute.
    *
    * @return The value of the "financedBy" attribute.
    */
   public String getFinancedBy() {
      return financedBy;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "loanApprovedDate" attribute.
    *
    * @return The value of the "loanApprovedDate" attribute.
    */
   public Date getLoanApprovedDate() {
      return loanApprovedDate;
   }
   /**
    * Returns the value of the "loanCreditScore" attribute.
    *
    * @return The value of the "loanCreditScore" attribute.
    */
   public String getLoanCreditScore() {
      return loanCreditScore;
   }
   /**
    * Returns the value of the "loanNumber" attribute.
    *
    * @return The value of the "loanNumber" attribute.
    */
   public String getLoanNumber() {
      return loanNumber;
   }
   /**
    * Returns the value of the "loanRate" attribute.
    *
    * @return The value of the "loanRate" attribute.
    */
   public String getLoanRate() {
      return loanRate;
   }
   /**
    * Returns the value of the "loanStatus" attribute.
    *
    * @return The value of the "loanStatus" attribute.
    */
   public String getLoanStatus() {
      return loanStatus;
   }
   /**
    * Returns the value of the "loanTerm" attribute.
    *
    * @return The value of the "loanTerm" attribute.
    */
   public String getLoanTerm() {
      return loanTerm;
   }
   /**
    * Returns the value of the "loanType" attribute.
    *
    * @return The value of the "loanType" attribute.
    */
   public String getLoanType() {
      return loanType;
   }
   /**
    * Returns the value of the "notes" attribute.
    *
    * @return The value of the "notes" attribute.
    */
   public String getNotes() {
      return notes;
   }
   /**
    * Returns the value of the "contract" attribute.
    *
    * @return The value of the "contract" attribute.
    */
   public Contract getContract() {
      return contract;
   }
   
   /**
    * Sets the value of the "contractId" attribute.
    *
    * @param contractId
    *     The value of the "contractId" attribute.
    */
   public void setContractId(String contractId) {
      this.contractId = contractId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "financedBy" attribute.
    *
    * @param financedBy
    *     The value of the "financedBy" attribute.
    */
   public void setFinancedBy(String financedBy) {
      this.financedBy = financedBy;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "loanApprovedDate" attribute.
    *
    * @param loanApprovedDate
    *     The value of the "loanApprovedDate" attribute.
    */
   public void setLoanApprovedDate(Date loanApprovedDate) {
      this.loanApprovedDate = loanApprovedDate;
   }
   /**
    * Sets the value of the "loanCreditScore" attribute.
    *
    * @param loanCreditScore
    *     The value of the "loanCreditScore" attribute.
    */
   public void setLoanCreditScore(String loanCreditScore) {
      this.loanCreditScore = loanCreditScore;
   }
   /**
    * Sets the value of the "loanNumber" attribute.
    *
    * @param loanNumber
    *     The value of the "loanNumber" attribute.
    */
   public void setLoanNumber(String loanNumber) {
      this.loanNumber = loanNumber;
   }
   /**
    * Sets the value of the "loanRate" attribute.
    *
    * @param loanRate
    *     The value of the "loanRate" attribute.
    */
   public void setLoanRate(String loanRate) {
      this.loanRate = loanRate;
   }
   /**
    * Sets the value of the "loanStatus" attribute.
    *
    * @param loanStatus
    *     The value of the "loanStatus" attribute.
    */
   public void setLoanStatus(String loanStatus) {
      this.loanStatus = loanStatus;
   }
   /**
    * Sets the value of the "loanTerm" attribute.
    *
    * @param loanTerm
    *     The value of the "loanTerm" attribute.
    */
   public void setLoanTerm(String loanTerm) {
      this.loanTerm = loanTerm;
   }
   /**
    * Sets the value of the "loanType" attribute.
    *
    * @param loanType
    *     The value of the "loanType" attribute.
    */
   public void setLoanType(String loanType) {
      this.loanType = loanType;
   }
   /**
    * Sets the value of the "notes" attribute.
    *
    * @param notes
    *     The value of the "notes" attribute.
    */
   public void setNotes(String notes) {
      this.notes = notes;
   }
   /**
    * Sets the value of the "contract" attribute.
    *
    * @param contract"
    *     The value of the "contract" attribute.
    */
   public void setContract(Contract contract) {
      this.contract = contract;
   }

}