/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Contract;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class PaymentHistory {

    private String companyId;
    private String contractId;
    private String createdBy;
    private Date createdDate;
    private String id;
    private boolean isActive;
    private Date lastUpdate;
    private String lastUpdateBy;
    private double paymentAmount;
    private String paymentAppliesTo;
    private Date paymentDate;
    private String paymentDescription;
    private String paymentMethod;
    private String paymentType;
    private Contract contract;

    /**
     * Constructor without parameter.
     * 
     */
    public PaymentHistory() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public PaymentHistory(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "contractId" attribute.
    *
    * @return The value of the "contractId" attribute.
    */
   public String getContractId() {
      return contractId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "paymentAmount" attribute.
    *
    * @return The value of the "paymentAmount" attribute.
    */
   public double getPaymentAmount() {
      return paymentAmount;
   }
   /**
    * Returns the value of the "paymentAppliesTo" attribute.
    *
    * @return The value of the "paymentAppliesTo" attribute.
    */
   public String getPaymentAppliesTo() {
      return paymentAppliesTo;
   }
   /**
    * Returns the value of the "paymentDate" attribute.
    *
    * @return The value of the "paymentDate" attribute.
    */
   public Date getPaymentDate() {
      return paymentDate;
   }
   /**
    * Returns the value of the "paymentDescription" attribute.
    *
    * @return The value of the "paymentDescription" attribute.
    */
   public String getPaymentDescription() {
      return paymentDescription;
   }
   /**
    * Returns the value of the "paymentMethod" attribute.
    *
    * @return The value of the "paymentMethod" attribute.
    */
   public String getPaymentMethod() {
      return paymentMethod;
   }
   /**
    * Returns the value of the "paymentType" attribute.
    *
    * @return The value of the "paymentType" attribute.
    */
   public String getPaymentType() {
      return paymentType;
   }
   /**
    * Returns the value of the "contract" attribute.
    *
    * @return The value of the "contract" attribute.
    */
   public Contract getContract() {
      return contract;
   }
   
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "contractId" attribute.
    *
    * @param contractId
    *     The value of the "contractId" attribute.
    */
   public void setContractId(String contractId) {
      this.contractId = contractId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "paymentAmount" attribute.
    *
    * @param paymentAmount
    *     The value of the "paymentAmount" attribute.
    */
   public void setPaymentAmount(double paymentAmount) {
      this.paymentAmount = paymentAmount;
   }
   /**
    * Sets the value of the "paymentAppliesTo" attribute.
    *
    * @param paymentAppliesTo
    *     The value of the "paymentAppliesTo" attribute.
    */
   public void setPaymentAppliesTo(String paymentAppliesTo) {
      this.paymentAppliesTo = paymentAppliesTo;
   }
   /**
    * Sets the value of the "paymentDate" attribute.
    *
    * @param paymentDate
    *     The value of the "paymentDate" attribute.
    */
   public void setPaymentDate(Date paymentDate) {
      this.paymentDate = paymentDate;
   }
   /**
    * Sets the value of the "paymentDescription" attribute.
    *
    * @param paymentDescription
    *     The value of the "paymentDescription" attribute.
    */
   public void setPaymentDescription(String paymentDescription) {
      this.paymentDescription = paymentDescription;
   }
   /**
    * Sets the value of the "paymentMethod" attribute.
    *
    * @param paymentMethod
    *     The value of the "paymentMethod" attribute.
    */
   public void setPaymentMethod(String paymentMethod) {
      this.paymentMethod = paymentMethod;
   }
   /**
    * Sets the value of the "paymentType" attribute.
    *
    * @param paymentType
    *     The value of the "paymentType" attribute.
    */
   public void setPaymentType(String paymentType) {
      this.paymentType = paymentType;
   }
   /**
    * Sets the value of the "contract" attribute.
    *
    * @param contract"
    *     The value of the "contract" attribute.
    */
   public void setContract(Contract contract) {
      this.contract = contract;
   }

}