/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Company;
import msharpmodel.JobProduct;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class ProcessStep {

    private Date actualEndDate;
    private Date actualStartDate;
    private String assignedEmployeeId;
    private String companyId;
    private String createdBy;
    private Date createdDate;
    private String description;
    private Date expectedEndDate;
    private Date expectedStartDate;
    private String id;
    private boolean isActive;
    private String jobProductId;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String note;
    private int stepOrder;
    private Company company;
    private JobProduct jobProduct;

    /**
     * Constructor without parameter.
     * 
     */
    public ProcessStep() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public ProcessStep(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "actualEndDate" attribute.
    *
    * @return The value of the "actualEndDate" attribute.
    */
   public Date getActualEndDate() {
      return actualEndDate;
   }
   /**
    * Returns the value of the "actualStartDate" attribute.
    *
    * @return The value of the "actualStartDate" attribute.
    */
   public Date getActualStartDate() {
      return actualStartDate;
   }
   /**
    * Returns the value of the "assignedEmployeeId" attribute.
    *
    * @return The value of the "assignedEmployeeId" attribute.
    */
   public String getAssignedEmployeeId() {
      return assignedEmployeeId;
   }
   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "description" attribute.
    *
    * @return The value of the "description" attribute.
    */
   public String getDescription() {
      return description;
   }
   /**
    * Returns the value of the "expectedEndDate" attribute.
    *
    * @return The value of the "expectedEndDate" attribute.
    */
   public Date getExpectedEndDate() {
      return expectedEndDate;
   }
   /**
    * Returns the value of the "expectedStartDate" attribute.
    *
    * @return The value of the "expectedStartDate" attribute.
    */
   public Date getExpectedStartDate() {
      return expectedStartDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "jobProductId" attribute.
    *
    * @return The value of the "jobProductId" attribute.
    */
   public String getJobProductId() {
      return jobProductId;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "note" attribute.
    *
    * @return The value of the "note" attribute.
    */
   public String getNote() {
      return note;
   }
   /**
    * Returns the value of the "stepOrder" attribute.
    *
    * @return The value of the "stepOrder" attribute.
    */
   public int getStepOrder() {
      return stepOrder;
   }
   /**
    * Returns the value of the "company" attribute.
    *
    * @return The value of the "company" attribute.
    */
   public Company getCompany() {
      return company;
   }
   
   /**
    * Returns the value of the "jobProduct" attribute.
    *
    * @return The value of the "jobProduct" attribute.
    */
   public JobProduct getJobProduct() {
      return jobProduct;
   }
   
   /**
    * Sets the value of the "actualEndDate" attribute.
    *
    * @param actualEndDate
    *     The value of the "actualEndDate" attribute.
    */
   public void setActualEndDate(Date actualEndDate) {
      this.actualEndDate = actualEndDate;
   }
   /**
    * Sets the value of the "actualStartDate" attribute.
    *
    * @param actualStartDate
    *     The value of the "actualStartDate" attribute.
    */
   public void setActualStartDate(Date actualStartDate) {
      this.actualStartDate = actualStartDate;
   }
   /**
    * Sets the value of the "assignedEmployeeId" attribute.
    *
    * @param assignedEmployeeId
    *     The value of the "assignedEmployeeId" attribute.
    */
   public void setAssignedEmployeeId(String assignedEmployeeId) {
      this.assignedEmployeeId = assignedEmployeeId;
   }
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "description" attribute.
    *
    * @param description
    *     The value of the "description" attribute.
    */
   public void setDescription(String description) {
      this.description = description;
   }
   /**
    * Sets the value of the "expectedEndDate" attribute.
    *
    * @param expectedEndDate
    *     The value of the "expectedEndDate" attribute.
    */
   public void setExpectedEndDate(Date expectedEndDate) {
      this.expectedEndDate = expectedEndDate;
   }
   /**
    * Sets the value of the "expectedStartDate" attribute.
    *
    * @param expectedStartDate
    *     The value of the "expectedStartDate" attribute.
    */
   public void setExpectedStartDate(Date expectedStartDate) {
      this.expectedStartDate = expectedStartDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "jobProductId" attribute.
    *
    * @param jobProductId
    *     The value of the "jobProductId" attribute.
    */
   public void setJobProductId(String jobProductId) {
      this.jobProductId = jobProductId;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "note" attribute.
    *
    * @param note
    *     The value of the "note" attribute.
    */
   public void setNote(String note) {
      this.note = note;
   }
   /**
    * Sets the value of the "stepOrder" attribute.
    *
    * @param stepOrder
    *     The value of the "stepOrder" attribute.
    */
   public void setStepOrder(int stepOrder) {
      this.stepOrder = stepOrder;
   }
   /**
    * Sets the value of the "company" attribute.
    *
    * @param company"
    *     The value of the "company" attribute.
    */
   public void setCompany(Company company) {
      this.company = company;
   }

   /**
    * Sets the value of the "jobProduct" attribute.
    *
    * @param jobProduct"
    *     The value of the "jobProduct" attribute.
    */
   public void setJobProduct(JobProduct jobProduct) {
      this.jobProduct = jobProduct;
   }

}