/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Inquiry;
import msharpmodel.ProductDetail;
import msharpmodel.ProductType;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class ProductInterest {

    private String id;
    private String inquiryId;
    private boolean isActive;
    private Date lastUpdate;
    private double priceQuoted;
    private String productDetailId;
    private String productTypeId;
    private Inquiry inquiry;
    private ProductDetail productDetail;
    private ProductType productType;

    /**
     * Constructor without parameter.
     * 
     */
    public ProductInterest() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public ProductInterest(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "inquiryId" attribute.
    *
    * @return The value of the "inquiryId" attribute.
    */
   public String getInquiryId() {
      return inquiryId;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "priceQuoted" attribute.
    *
    * @return The value of the "priceQuoted" attribute.
    */
   public double getPriceQuoted() {
      return priceQuoted;
   }
   /**
    * Returns the value of the "productDetailId" attribute.
    *
    * @return The value of the "productDetailId" attribute.
    */
   public String getProductDetailId() {
      return productDetailId;
   }
   /**
    * Returns the value of the "productTypeId" attribute.
    *
    * @return The value of the "productTypeId" attribute.
    */
   public String getProductTypeId() {
      return productTypeId;
   }
   /**
    * Returns the value of the "inquiry" attribute.
    *
    * @return The value of the "inquiry" attribute.
    */
   public Inquiry getInquiry() {
      return inquiry;
   }
   
   /**
    * Returns the value of the "productDetail" attribute.
    *
    * @return The value of the "productDetail" attribute.
    */
   public ProductDetail getProductDetail() {
      return productDetail;
   }
   
   /**
    * Returns the value of the "productType" attribute.
    *
    * @return The value of the "productType" attribute.
    */
   public ProductType getProductType() {
      return productType;
   }
   
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "inquiryId" attribute.
    *
    * @param inquiryId
    *     The value of the "inquiryId" attribute.
    */
   public void setInquiryId(String inquiryId) {
      this.inquiryId = inquiryId;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "priceQuoted" attribute.
    *
    * @param priceQuoted
    *     The value of the "priceQuoted" attribute.
    */
   public void setPriceQuoted(double priceQuoted) {
      this.priceQuoted = priceQuoted;
   }
   /**
    * Sets the value of the "productDetailId" attribute.
    *
    * @param productDetailId
    *     The value of the "productDetailId" attribute.
    */
   public void setProductDetailId(String productDetailId) {
      this.productDetailId = productDetailId;
   }
   /**
    * Sets the value of the "productTypeId" attribute.
    *
    * @param productTypeId
    *     The value of the "productTypeId" attribute.
    */
   public void setProductTypeId(String productTypeId) {
      this.productTypeId = productTypeId;
   }
   /**
    * Sets the value of the "inquiry" attribute.
    *
    * @param inquiry"
    *     The value of the "inquiry" attribute.
    */
   public void setInquiry(Inquiry inquiry) {
      this.inquiry = inquiry;
   }

   /**
    * Sets the value of the "productDetail" attribute.
    *
    * @param productDetail"
    *     The value of the "productDetail" attribute.
    */
   public void setProductDetail(ProductDetail productDetail) {
      this.productDetail = productDetail;
   }

   /**
    * Sets the value of the "productType" attribute.
    *
    * @param productType"
    *     The value of the "productType" attribute.
    */
   public void setProductType(ProductType productType) {
      this.productType = productType;
   }

}