/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Appointment;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Proposal {

    private String appointmentId;
    private String companyId;
    private String createdBy;
    private Date createdDate;
    private Date date;
    private Date dateDelivered;
    private double discountedPrice;
    private double discountOffered;
    private String id;
    private boolean isActive;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String note;
    private double priceQuoted;
    private boolean sent;
    private String status;
    private Appointment appointment;

    /**
     * Constructor without parameter.
     * 
     */
    public Proposal() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Proposal(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "appointmentId" attribute.
    *
    * @return The value of the "appointmentId" attribute.
    */
   public String getAppointmentId() {
      return appointmentId;
   }
   /**
    * Returns the value of the "companyId" attribute.
    *
    * @return The value of the "companyId" attribute.
    */
   public String getCompanyId() {
      return companyId;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "date" attribute.
    *
    * @return The value of the "date" attribute.
    */
   public Date getDate() {
      return date;
   }
   /**
    * Returns the value of the "dateDelivered" attribute.
    *
    * @return The value of the "dateDelivered" attribute.
    */
   public Date getDateDelivered() {
      return dateDelivered;
   }
   /**
    * Returns the value of the "discountedPrice" attribute.
    *
    * @return The value of the "discountedPrice" attribute.
    */
   public double getDiscountedPrice() {
      return discountedPrice;
   }
   /**
    * Returns the value of the "discountOffered" attribute.
    *
    * @return The value of the "discountOffered" attribute.
    */
   public double getDiscountOffered() {
      return discountOffered;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "note" attribute.
    *
    * @return The value of the "note" attribute.
    */
   public String getNote() {
      return note;
   }
   /**
    * Returns the value of the "priceQuoted" attribute.
    *
    * @return The value of the "priceQuoted" attribute.
    */
   public double getPriceQuoted() {
      return priceQuoted;
   }
   /**
    * Returns the value of the "sent" attribute.
    *
    * @return The value of the "sent" attribute.
    */
   public boolean getSent() {
      return sent;
   }
   /**
    * Returns the value of the "status" attribute.
    *
    * @return The value of the "status" attribute.
    */
   public String getStatus() {
      return status;
   }
   /**
    * Returns the value of the "appointment" attribute.
    *
    * @return The value of the "appointment" attribute.
    */
   public Appointment getAppointment() {
      return appointment;
   }
   
   /**
    * Sets the value of the "appointmentId" attribute.
    *
    * @param appointmentId
    *     The value of the "appointmentId" attribute.
    */
   public void setAppointmentId(String appointmentId) {
      this.appointmentId = appointmentId;
   }
   /**
    * Sets the value of the "companyId" attribute.
    *
    * @param companyId
    *     The value of the "companyId" attribute.
    */
   public void setCompanyId(String companyId) {
      this.companyId = companyId;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "date" attribute.
    *
    * @param date
    *     The value of the "date" attribute.
    */
   public void setDate(Date date) {
      this.date = date;
   }
   /**
    * Sets the value of the "dateDelivered" attribute.
    *
    * @param dateDelivered
    *     The value of the "dateDelivered" attribute.
    */
   public void setDateDelivered(Date dateDelivered) {
      this.dateDelivered = dateDelivered;
   }
   /**
    * Sets the value of the "discountedPrice" attribute.
    *
    * @param discountedPrice
    *     The value of the "discountedPrice" attribute.
    */
   public void setDiscountedPrice(double discountedPrice) {
      this.discountedPrice = discountedPrice;
   }
   /**
    * Sets the value of the "discountOffered" attribute.
    *
    * @param discountOffered
    *     The value of the "discountOffered" attribute.
    */
   public void setDiscountOffered(double discountOffered) {
      this.discountOffered = discountOffered;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "note" attribute.
    *
    * @param note
    *     The value of the "note" attribute.
    */
   public void setNote(String note) {
      this.note = note;
   }
   /**
    * Sets the value of the "priceQuoted" attribute.
    *
    * @param priceQuoted
    *     The value of the "priceQuoted" attribute.
    */
   public void setPriceQuoted(double priceQuoted) {
      this.priceQuoted = priceQuoted;
   }
   /**
    * Sets the value of the "sent" attribute.
    *
    * @param sent
    *     The value of the "sent" attribute.
    */
   public void setSent(boolean sent) {
      this.sent = sent;
   }
   /**
    * Sets the value of the "status" attribute.
    *
    * @param status
    *     The value of the "status" attribute.
    */
   public void setStatus(String status) {
      this.status = status;
   }
   /**
    * Sets the value of the "appointment" attribute.
    *
    * @param appointment"
    *     The value of the "appointment" attribute.
    */
   public void setAppointment(Appointment appointment) {
      this.appointment = appointment;
   }

}