/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.JobProduct;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class ServiceOrder {

    private double amountPaid;
    private Date completedDate;
    private String createdBy;
    private Date createdDate;
    private String id;
    private boolean isActive;
    private boolean isBillable;
    private boolean isWarranty;
    private String jobProductId;
    private Date lastUpdate;
    private String lastUpdateBy;
    private Date requestDate;
    private double serviceAmount;
    private Date serviceDate;
    private String serviceNote;
    private String serviceType;
    private String status;
    private String technicianEmployeeId;
    private String technicianNote;
    private JobProduct jobProduct;

    /**
     * Constructor without parameter.
     * 
     */
    public ServiceOrder() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public ServiceOrder(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "amountPaid" attribute.
    *
    * @return The value of the "amountPaid" attribute.
    */
   public double getAmountPaid() {
      return amountPaid;
   }
   /**
    * Returns the value of the "completedDate" attribute.
    *
    * @return The value of the "completedDate" attribute.
    */
   public Date getCompletedDate() {
      return completedDate;
   }
   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "isBillable" attribute.
    *
    * @return The value of the "isBillable" attribute.
    */
   public boolean getIsBillable() {
      return isBillable;
   }
   /**
    * Returns the value of the "isWarranty" attribute.
    *
    * @return The value of the "isWarranty" attribute.
    */
   public boolean getIsWarranty() {
      return isWarranty;
   }
   /**
    * Returns the value of the "jobProductId" attribute.
    *
    * @return The value of the "jobProductId" attribute.
    */
   public String getJobProductId() {
      return jobProductId;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "requestDate" attribute.
    *
    * @return The value of the "requestDate" attribute.
    */
   public Date getRequestDate() {
      return requestDate;
   }
   /**
    * Returns the value of the "serviceAmount" attribute.
    *
    * @return The value of the "serviceAmount" attribute.
    */
   public double getServiceAmount() {
      return serviceAmount;
   }
   /**
    * Returns the value of the "serviceDate" attribute.
    *
    * @return The value of the "serviceDate" attribute.
    */
   public Date getServiceDate() {
      return serviceDate;
   }
   /**
    * Returns the value of the "serviceNote" attribute.
    *
    * @return The value of the "serviceNote" attribute.
    */
   public String getServiceNote() {
      return serviceNote;
   }
   /**
    * Returns the value of the "serviceType" attribute.
    *
    * @return The value of the "serviceType" attribute.
    */
   public String getServiceType() {
      return serviceType;
   }
   /**
    * Returns the value of the "status" attribute.
    *
    * @return The value of the "status" attribute.
    */
   public String getStatus() {
      return status;
   }
   /**
    * Returns the value of the "technicianEmployeeId" attribute.
    *
    * @return The value of the "technicianEmployeeId" attribute.
    */
   public String getTechnicianEmployeeId() {
      return technicianEmployeeId;
   }
   /**
    * Returns the value of the "technicianNote" attribute.
    *
    * @return The value of the "technicianNote" attribute.
    */
   public String getTechnicianNote() {
      return technicianNote;
   }
   /**
    * Returns the value of the "jobProduct" attribute.
    *
    * @return The value of the "jobProduct" attribute.
    */
   public JobProduct getJobProduct() {
      return jobProduct;
   }
   
   /**
    * Sets the value of the "amountPaid" attribute.
    *
    * @param amountPaid
    *     The value of the "amountPaid" attribute.
    */
   public void setAmountPaid(double amountPaid) {
      this.amountPaid = amountPaid;
   }
   /**
    * Sets the value of the "completedDate" attribute.
    *
    * @param completedDate
    *     The value of the "completedDate" attribute.
    */
   public void setCompletedDate(Date completedDate) {
      this.completedDate = completedDate;
   }
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "isBillable" attribute.
    *
    * @param isBillable
    *     The value of the "isBillable" attribute.
    */
   public void setIsBillable(boolean isBillable) {
      this.isBillable = isBillable;
   }
   /**
    * Sets the value of the "isWarranty" attribute.
    *
    * @param isWarranty
    *     The value of the "isWarranty" attribute.
    */
   public void setIsWarranty(boolean isWarranty) {
      this.isWarranty = isWarranty;
   }
   /**
    * Sets the value of the "jobProductId" attribute.
    *
    * @param jobProductId
    *     The value of the "jobProductId" attribute.
    */
   public void setJobProductId(String jobProductId) {
      this.jobProductId = jobProductId;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "requestDate" attribute.
    *
    * @param requestDate
    *     The value of the "requestDate" attribute.
    */
   public void setRequestDate(Date requestDate) {
      this.requestDate = requestDate;
   }
   /**
    * Sets the value of the "serviceAmount" attribute.
    *
    * @param serviceAmount
    *     The value of the "serviceAmount" attribute.
    */
   public void setServiceAmount(double serviceAmount) {
      this.serviceAmount = serviceAmount;
   }
   /**
    * Sets the value of the "serviceDate" attribute.
    *
    * @param serviceDate
    *     The value of the "serviceDate" attribute.
    */
   public void setServiceDate(Date serviceDate) {
      this.serviceDate = serviceDate;
   }
   /**
    * Sets the value of the "serviceNote" attribute.
    *
    * @param serviceNote
    *     The value of the "serviceNote" attribute.
    */
   public void setServiceNote(String serviceNote) {
      this.serviceNote = serviceNote;
   }
   /**
    * Sets the value of the "serviceType" attribute.
    *
    * @param serviceType
    *     The value of the "serviceType" attribute.
    */
   public void setServiceType(String serviceType) {
      this.serviceType = serviceType;
   }
   /**
    * Sets the value of the "status" attribute.
    *
    * @param status
    *     The value of the "status" attribute.
    */
   public void setStatus(String status) {
      this.status = status;
   }
   /**
    * Sets the value of the "technicianEmployeeId" attribute.
    *
    * @param technicianEmployeeId
    *     The value of the "technicianEmployeeId" attribute.
    */
   public void setTechnicianEmployeeId(String technicianEmployeeId) {
      this.technicianEmployeeId = technicianEmployeeId;
   }
   /**
    * Sets the value of the "technicianNote" attribute.
    *
    * @param technicianNote
    *     The value of the "technicianNote" attribute.
    */
   public void setTechnicianNote(String technicianNote) {
      this.technicianNote = technicianNote;
   }
   /**
    * Sets the value of the "jobProduct" attribute.
    *
    * @param jobProduct"
    *     The value of the "jobProduct" attribute.
    */
   public void setJobProduct(JobProduct jobProduct) {
      this.jobProduct = jobProduct;
   }

}