/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package msharpmodel;


import java.util.Date;
import msharpmodel.Job;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:57241/WcfDataService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Survey {

    private String createdBy;
    private Date createdDate;
    private String id;
    private String installationCrewRating;
    private boolean isActive;
    private String jobId;
    private Date lastUpdate;
    private String lastUpdateBy;
    private String officeStaffRating;
    private String otherEstimates;
    private String overallSatisfaction;
    private String purchaseReason;
    private String salesRepRating;
    private String valueOfHome;
    private String wouldReferOthers;
    private Job job;

    /**
     * Constructor without parameter.
     * 
     */
    public Survey() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Survey(String id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "createdBy" attribute.
    *
    * @return The value of the "createdBy" attribute.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   /**
    * Returns the value of the "createdDate" attribute.
    *
    * @return The value of the "createdDate" attribute.
    */
   public Date getCreatedDate() {
      return createdDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public String getId() {
      return id;
   }
   /**
    * Returns the value of the "installationCrewRating" attribute.
    *
    * @return The value of the "installationCrewRating" attribute.
    */
   public String getInstallationCrewRating() {
      return installationCrewRating;
   }
   /**
    * Returns the value of the "isActive" attribute.
    *
    * @return The value of the "isActive" attribute.
    */
   public boolean getIsActive() {
      return isActive;
   }
   /**
    * Returns the value of the "jobId" attribute.
    *
    * @return The value of the "jobId" attribute.
    */
   public String getJobId() {
      return jobId;
   }
   /**
    * Returns the value of the "lastUpdate" attribute.
    *
    * @return The value of the "lastUpdate" attribute.
    */
   public Date getLastUpdate() {
      return lastUpdate;
   }
   /**
    * Returns the value of the "lastUpdateBy" attribute.
    *
    * @return The value of the "lastUpdateBy" attribute.
    */
   public String getLastUpdateBy() {
      return lastUpdateBy;
   }
   /**
    * Returns the value of the "officeStaffRating" attribute.
    *
    * @return The value of the "officeStaffRating" attribute.
    */
   public String getOfficeStaffRating() {
      return officeStaffRating;
   }
   /**
    * Returns the value of the "otherEstimates" attribute.
    *
    * @return The value of the "otherEstimates" attribute.
    */
   public String getOtherEstimates() {
      return otherEstimates;
   }
   /**
    * Returns the value of the "overallSatisfaction" attribute.
    *
    * @return The value of the "overallSatisfaction" attribute.
    */
   public String getOverallSatisfaction() {
      return overallSatisfaction;
   }
   /**
    * Returns the value of the "purchaseReason" attribute.
    *
    * @return The value of the "purchaseReason" attribute.
    */
   public String getPurchaseReason() {
      return purchaseReason;
   }
   /**
    * Returns the value of the "salesRepRating" attribute.
    *
    * @return The value of the "salesRepRating" attribute.
    */
   public String getSalesRepRating() {
      return salesRepRating;
   }
   /**
    * Returns the value of the "valueOfHome" attribute.
    *
    * @return The value of the "valueOfHome" attribute.
    */
   public String getValueOfHome() {
      return valueOfHome;
   }
   /**
    * Returns the value of the "wouldReferOthers" attribute.
    *
    * @return The value of the "wouldReferOthers" attribute.
    */
   public String getWouldReferOthers() {
      return wouldReferOthers;
   }
   /**
    * Returns the value of the "job" attribute.
    *
    * @return The value of the "job" attribute.
    */
   public Job getJob() {
      return job;
   }
   
   /**
    * Sets the value of the "createdBy" attribute.
    *
    * @param createdBy
    *     The value of the "createdBy" attribute.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   /**
    * Sets the value of the "createdDate" attribute.
    *
    * @param createdDate
    *     The value of the "createdDate" attribute.
    */
   public void setCreatedDate(Date createdDate) {
      this.createdDate = createdDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   /**
    * Sets the value of the "installationCrewRating" attribute.
    *
    * @param installationCrewRating
    *     The value of the "installationCrewRating" attribute.
    */
   public void setInstallationCrewRating(String installationCrewRating) {
      this.installationCrewRating = installationCrewRating;
   }
   /**
    * Sets the value of the "isActive" attribute.
    *
    * @param isActive
    *     The value of the "isActive" attribute.
    */
   public void setIsActive(boolean isActive) {
      this.isActive = isActive;
   }
   /**
    * Sets the value of the "jobId" attribute.
    *
    * @param jobId
    *     The value of the "jobId" attribute.
    */
   public void setJobId(String jobId) {
      this.jobId = jobId;
   }
   /**
    * Sets the value of the "lastUpdate" attribute.
    *
    * @param lastUpdate
    *     The value of the "lastUpdate" attribute.
    */
   public void setLastUpdate(Date lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   /**
    * Sets the value of the "lastUpdateBy" attribute.
    *
    * @param lastUpdateBy
    *     The value of the "lastUpdateBy" attribute.
    */
   public void setLastUpdateBy(String lastUpdateBy) {
      this.lastUpdateBy = lastUpdateBy;
   }
   /**
    * Sets the value of the "officeStaffRating" attribute.
    *
    * @param officeStaffRating
    *     The value of the "officeStaffRating" attribute.
    */
   public void setOfficeStaffRating(String officeStaffRating) {
      this.officeStaffRating = officeStaffRating;
   }
   /**
    * Sets the value of the "otherEstimates" attribute.
    *
    * @param otherEstimates
    *     The value of the "otherEstimates" attribute.
    */
   public void setOtherEstimates(String otherEstimates) {
      this.otherEstimates = otherEstimates;
   }
   /**
    * Sets the value of the "overallSatisfaction" attribute.
    *
    * @param overallSatisfaction
    *     The value of the "overallSatisfaction" attribute.
    */
   public void setOverallSatisfaction(String overallSatisfaction) {
      this.overallSatisfaction = overallSatisfaction;
   }
   /**
    * Sets the value of the "purchaseReason" attribute.
    *
    * @param purchaseReason
    *     The value of the "purchaseReason" attribute.
    */
   public void setPurchaseReason(String purchaseReason) {
      this.purchaseReason = purchaseReason;
   }
   /**
    * Sets the value of the "salesRepRating" attribute.
    *
    * @param salesRepRating
    *     The value of the "salesRepRating" attribute.
    */
   public void setSalesRepRating(String salesRepRating) {
      this.salesRepRating = salesRepRating;
   }
   /**
    * Sets the value of the "valueOfHome" attribute.
    *
    * @param valueOfHome
    *     The value of the "valueOfHome" attribute.
    */
   public void setValueOfHome(String valueOfHome) {
      this.valueOfHome = valueOfHome;
   }
   /**
    * Sets the value of the "wouldReferOthers" attribute.
    *
    * @param wouldReferOthers
    *     The value of the "wouldReferOthers" attribute.
    */
   public void setWouldReferOthers(String wouldReferOthers) {
      this.wouldReferOthers = wouldReferOthers;
   }
   /**
    * Sets the value of the "job" attribute.
    *
    * @param job"
    *     The value of the "job" attribute.
    */
   public void setJob(Job job) {
      this.job = job;
   }

}